/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoTestStepModel from './AutoTestStepModel';
import ConfigurationShortModel from './ConfigurationShortModel';
import LabelShortModel from './LabelShortModel';
import LinkPutModel from './LinkPutModel';
import TestStatusModel from './TestStatusModel';

/**
 * The AutoTestModel model module.
 * @module model/AutoTestModel
 * @version 1.0.0
 */
class AutoTestModel {
    /**
     * Constructs a new <code>AutoTestModel</code>.
     * @alias module:model/AutoTestModel
     * @param globalId {Number} Global ID of the autotest
     * @param isDeleted {Boolean} Indicates if the autotest is deleted
     * @param mustBeApproved {Boolean} Indicates if the autotest has unapproved changes from linked work items
     * @param id {String} Unique ID of the autotest
     * @param createdDate {Date} Creation date of the autotest
     * @param createdById {String} Unique ID of the project creator
     * @param externalId {String} External ID of the autotest
     * @param projectId {String} Unique ID of the autotest project
     * @param name {String} Name of the autotest
     */
    constructor(globalId, isDeleted, mustBeApproved, id, createdDate, createdById, externalId, projectId, name) { 
        
        AutoTestModel.initialize(this, globalId, isDeleted, mustBeApproved, id, createdDate, createdById, externalId, projectId, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, globalId, isDeleted, mustBeApproved, id, createdDate, createdById, externalId, projectId, name) { 
        obj['globalId'] = globalId;
        obj['isDeleted'] = isDeleted;
        obj['mustBeApproved'] = mustBeApproved;
        obj['id'] = id;
        obj['createdDate'] = createdDate;
        obj['createdById'] = createdById;
        obj['externalId'] = externalId;
        obj['projectId'] = projectId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>AutoTestModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoTestModel} obj Optional instance to populate.
     * @return {module:model/AutoTestModel} The populated <code>AutoTestModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoTestModel();

            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('mustBeApproved')) {
                obj['mustBeApproved'] = ApiClient.convertToType(data['mustBeApproved'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('modifiedDate')) {
                obj['modifiedDate'] = ApiClient.convertToType(data['modifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdById')) {
                obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
            }
            if (data.hasOwnProperty('modifiedById')) {
                obj['modifiedById'] = ApiClient.convertToType(data['modifiedById'], 'String');
            }
            if (data.hasOwnProperty('lastTestRunId')) {
                obj['lastTestRunId'] = ApiClient.convertToType(data['lastTestRunId'], 'String');
            }
            if (data.hasOwnProperty('lastTestRunName')) {
                obj['lastTestRunName'] = ApiClient.convertToType(data['lastTestRunName'], 'String');
            }
            if (data.hasOwnProperty('lastTestResultId')) {
                obj['lastTestResultId'] = ApiClient.convertToType(data['lastTestResultId'], 'String');
            }
            if (data.hasOwnProperty('lastTestResultConfiguration')) {
                obj['lastTestResultConfiguration'] = ApiClient.convertToType(data['lastTestResultConfiguration'], ConfigurationShortModel);
            }
            if (data.hasOwnProperty('lastTestResultOutcome')) {
                obj['lastTestResultOutcome'] = ApiClient.convertToType(data['lastTestResultOutcome'], 'String');
            }
            if (data.hasOwnProperty('lastTestResultStatus')) {
                obj['lastTestResultStatus'] = ApiClient.convertToType(data['lastTestResultStatus'], TestStatusModel);
            }
            if (data.hasOwnProperty('stabilityPercentage')) {
                obj['stabilityPercentage'] = ApiClient.convertToType(data['stabilityPercentage'], 'Number');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LinkPutModel]);
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('classname')) {
                obj['classname'] = ApiClient.convertToType(data['classname'], 'String');
            }
            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [AutoTestStepModel]);
            }
            if (data.hasOwnProperty('setup')) {
                obj['setup'] = ApiClient.convertToType(data['setup'], [AutoTestStepModel]);
            }
            if (data.hasOwnProperty('teardown')) {
                obj['teardown'] = ApiClient.convertToType(data['teardown'], [AutoTestStepModel]);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], [LabelShortModel]);
            }
            if (data.hasOwnProperty('isFlaky')) {
                obj['isFlaky'] = ApiClient.convertToType(data['isFlaky'], 'Boolean');
            }
            if (data.hasOwnProperty('externalKey')) {
                obj['externalKey'] = ApiClient.convertToType(data['externalKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoTestModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoTestModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AutoTestModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['createdById'] && !(typeof data['createdById'] === 'string' || data['createdById'] instanceof String)) {
            throw new Error("Expected the field `createdById` to be a primitive type in the JSON string but got " + data['createdById']);
        }
        // ensure the json data is a string
        if (data['modifiedById'] && !(typeof data['modifiedById'] === 'string' || data['modifiedById'] instanceof String)) {
            throw new Error("Expected the field `modifiedById` to be a primitive type in the JSON string but got " + data['modifiedById']);
        }
        // ensure the json data is a string
        if (data['lastTestRunId'] && !(typeof data['lastTestRunId'] === 'string' || data['lastTestRunId'] instanceof String)) {
            throw new Error("Expected the field `lastTestRunId` to be a primitive type in the JSON string but got " + data['lastTestRunId']);
        }
        // ensure the json data is a string
        if (data['lastTestRunName'] && !(typeof data['lastTestRunName'] === 'string' || data['lastTestRunName'] instanceof String)) {
            throw new Error("Expected the field `lastTestRunName` to be a primitive type in the JSON string but got " + data['lastTestRunName']);
        }
        // ensure the json data is a string
        if (data['lastTestResultId'] && !(typeof data['lastTestResultId'] === 'string' || data['lastTestResultId'] instanceof String)) {
            throw new Error("Expected the field `lastTestResultId` to be a primitive type in the JSON string but got " + data['lastTestResultId']);
        }
        // validate the optional field `lastTestResultConfiguration`
        if (data['lastTestResultConfiguration']) { // data not null
          ConfigurationShortModel.validateJSON(data['lastTestResultConfiguration']);
        }
        // ensure the json data is a string
        if (data['lastTestResultOutcome'] && !(typeof data['lastTestResultOutcome'] === 'string' || data['lastTestResultOutcome'] instanceof String)) {
            throw new Error("Expected the field `lastTestResultOutcome` to be a primitive type in the JSON string but got " + data['lastTestResultOutcome']);
        }
        // validate the optional field `lastTestResultStatus`
        if (data['lastTestResultStatus']) { // data not null
          TestStatusModel.validateJSON(data['lastTestResultStatus']);
        }
        // ensure the json data is a string
        if (data['externalId'] && !(typeof data['externalId'] === 'string' || data['externalId'] instanceof String)) {
            throw new Error("Expected the field `externalId` to be a primitive type in the JSON string but got " + data['externalId']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LinkPutModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['namespace'] && !(typeof data['namespace'] === 'string' || data['namespace'] instanceof String)) {
            throw new Error("Expected the field `namespace` to be a primitive type in the JSON string but got " + data['namespace']);
        }
        // ensure the json data is a string
        if (data['classname'] && !(typeof data['classname'] === 'string' || data['classname'] instanceof String)) {
            throw new Error("Expected the field `classname` to be a primitive type in the JSON string but got " + data['classname']);
        }
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                AutoTestStepModel.validateJSON(item);
            };
        }
        if (data['setup']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['setup'])) {
                throw new Error("Expected the field `setup` to be an array in the JSON data but got " + data['setup']);
            }
            // validate the optional field `setup` (array)
            for (const item of data['setup']) {
                AutoTestStepModel.validateJSON(item);
            };
        }
        if (data['teardown']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teardown'])) {
                throw new Error("Expected the field `teardown` to be an array in the JSON data but got " + data['teardown']);
            }
            // validate the optional field `teardown` (array)
            for (const item of data['teardown']) {
                AutoTestStepModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['labels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['labels'])) {
                throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
            }
            // validate the optional field `labels` (array)
            for (const item of data['labels']) {
                LabelShortModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['externalKey'] && !(typeof data['externalKey'] === 'string' || data['externalKey'] instanceof String)) {
            throw new Error("Expected the field `externalKey` to be a primitive type in the JSON string but got " + data['externalKey']);
        }

        return true;
    }


}

AutoTestModel.RequiredProperties = ["globalId", "isDeleted", "mustBeApproved", "id", "createdDate", "createdById", "externalId", "projectId", "name"];

/**
 * Global ID of the autotest
 * @member {Number} globalId
 */
AutoTestModel.prototype['globalId'] = undefined;

/**
 * Indicates if the autotest is deleted
 * @member {Boolean} isDeleted
 */
AutoTestModel.prototype['isDeleted'] = undefined;

/**
 * Indicates if the autotest has unapproved changes from linked work items
 * @member {Boolean} mustBeApproved
 */
AutoTestModel.prototype['mustBeApproved'] = undefined;

/**
 * Unique ID of the autotest
 * @member {String} id
 */
AutoTestModel.prototype['id'] = undefined;

/**
 * Creation date of the autotest
 * @member {Date} createdDate
 */
AutoTestModel.prototype['createdDate'] = undefined;

/**
 * Last modification date of the project
 * @member {Date} modifiedDate
 */
AutoTestModel.prototype['modifiedDate'] = undefined;

/**
 * Unique ID of the project creator
 * @member {String} createdById
 */
AutoTestModel.prototype['createdById'] = undefined;

/**
 * Unique ID of the project last editor
 * @member {String} modifiedById
 */
AutoTestModel.prototype['modifiedById'] = undefined;

/**
 * Unique ID of the autotest last test run
 * @member {String} lastTestRunId
 */
AutoTestModel.prototype['lastTestRunId'] = undefined;

/**
 * Name of the autotest last test run
 * @member {String} lastTestRunName
 */
AutoTestModel.prototype['lastTestRunName'] = undefined;

/**
 * Unique ID of the autotest last test result
 * @member {String} lastTestResultId
 */
AutoTestModel.prototype['lastTestResultId'] = undefined;

/**
 * Configuration of the autotest last test result
 * @member {module:model/ConfigurationShortModel} lastTestResultConfiguration
 */
AutoTestModel.prototype['lastTestResultConfiguration'] = undefined;

/**
 * Outcome of the autotest last test result
 * @member {String} lastTestResultOutcome
 */
AutoTestModel.prototype['lastTestResultOutcome'] = undefined;

/**
 * Status of the autotest last test result
 * @member {module:model/TestStatusModel} lastTestResultStatus
 */
AutoTestModel.prototype['lastTestResultStatus'] = undefined;

/**
 * Stability percentage of the autotest
 * @member {Number} stabilityPercentage
 */
AutoTestModel.prototype['stabilityPercentage'] = undefined;

/**
 * External ID of the autotest
 * @member {String} externalId
 */
AutoTestModel.prototype['externalId'] = undefined;

/**
 * Collection of the autotest links
 * @member {Array.<module:model/LinkPutModel>} links
 */
AutoTestModel.prototype['links'] = undefined;

/**
 * Unique ID of the autotest project
 * @member {String} projectId
 */
AutoTestModel.prototype['projectId'] = undefined;

/**
 * Name of the autotest
 * @member {String} name
 */
AutoTestModel.prototype['name'] = undefined;

/**
 * Name of the autotest namespace
 * @member {String} namespace
 */
AutoTestModel.prototype['namespace'] = undefined;

/**
 * Name of the autotest class
 * @member {String} classname
 */
AutoTestModel.prototype['classname'] = undefined;

/**
 * Collection of the autotest steps
 * @member {Array.<module:model/AutoTestStepModel>} steps
 */
AutoTestModel.prototype['steps'] = undefined;

/**
 * Collection of the autotest setup steps
 * @member {Array.<module:model/AutoTestStepModel>} setup
 */
AutoTestModel.prototype['setup'] = undefined;

/**
 * Collection of the autotest teardown steps
 * @member {Array.<module:model/AutoTestStepModel>} teardown
 */
AutoTestModel.prototype['teardown'] = undefined;

/**
 * Name of the autotest in autotest's card
 * @member {String} title
 */
AutoTestModel.prototype['title'] = undefined;

/**
 * Description of the autotest in autotest's card
 * @member {String} description
 */
AutoTestModel.prototype['description'] = undefined;

/**
 * Collection of the autotest labels
 * @member {Array.<module:model/LabelShortModel>} labels
 */
AutoTestModel.prototype['labels'] = undefined;

/**
 * Indicates if the autotest is marked as flaky
 * @member {Boolean} isFlaky
 */
AutoTestModel.prototype['isFlaky'] = undefined;

/**
 * External key of the autotest
 * @member {String} externalKey
 */
AutoTestModel.prototype['externalKey'] = undefined;






export default AutoTestModel;

