/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AutoTestSearchIncludeApiModel model module.
 * @module model/AutoTestSearchIncludeApiModel
 * @version 1.0.0
 */
class AutoTestSearchIncludeApiModel {
    /**
     * Constructs a new <code>AutoTestSearchIncludeApiModel</code>.
     * @alias module:model/AutoTestSearchIncludeApiModel
     */
    constructor() { 
        
        AutoTestSearchIncludeApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutoTestSearchIncludeApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoTestSearchIncludeApiModel} obj Optional instance to populate.
     * @return {module:model/AutoTestSearchIncludeApiModel} The populated <code>AutoTestSearchIncludeApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoTestSearchIncludeApiModel();

            if (data.hasOwnProperty('includeSteps')) {
                obj['includeSteps'] = ApiClient.convertToType(data['includeSteps'], 'Boolean');
            }
            if (data.hasOwnProperty('includeLinks')) {
                obj['includeLinks'] = ApiClient.convertToType(data['includeLinks'], 'Boolean');
            }
            if (data.hasOwnProperty('includeLabels')) {
                obj['includeLabels'] = ApiClient.convertToType(data['includeLabels'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoTestSearchIncludeApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoTestSearchIncludeApiModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * If autotest steps will be included
 * @member {Boolean} includeSteps
 */
AutoTestSearchIncludeApiModel.prototype['includeSteps'] = undefined;

/**
 * If autotest links will be included
 * @member {Boolean} includeLinks
 */
AutoTestSearchIncludeApiModel.prototype['includeLinks'] = undefined;

/**
 * If autotest labels will be included
 * @member {Boolean} includeLabels
 */
AutoTestSearchIncludeApiModel.prototype['includeLabels'] = undefined;






export default AutoTestSearchIncludeApiModel;

