/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttachmentApiResult from './AttachmentApiResult';
import AvailableTestResultOutcome from './AvailableTestResultOutcome';

/**
 * The AutoTestStepResult model module.
 * @module model/AutoTestStepResult
 * @version 1.0.0
 */
class AutoTestStepResult {
    /**
     * Constructs a new <code>AutoTestStepResult</code>.
     * @alias module:model/AutoTestStepResult
     */
    constructor() { 
        
        AutoTestStepResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutoTestStepResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoTestStepResult} obj Optional instance to populate.
     * @return {module:model/AutoTestStepResult} The populated <code>AutoTestStepResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoTestStepResult();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = ApiClient.convertToType(data['info'], 'String');
            }
            if (data.hasOwnProperty('startedOn')) {
                obj['startedOn'] = ApiClient.convertToType(data['startedOn'], 'Date');
            }
            if (data.hasOwnProperty('completedOn')) {
                obj['completedOn'] = ApiClient.convertToType(data['completedOn'], 'Date');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('outcome')) {
                obj['outcome'] = ApiClient.convertToType(data['outcome'], AvailableTestResultOutcome);
            }
            if (data.hasOwnProperty('stepResults')) {
                obj['stepResults'] = ApiClient.convertToType(data['stepResults'], [AutoTestStepResult]);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AttachmentApiResult]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoTestStepResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoTestStepResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['info'] && !(typeof data['info'] === 'string' || data['info'] instanceof String)) {
            throw new Error("Expected the field `info` to be a primitive type in the JSON string but got " + data['info']);
        }
        if (data['stepResults']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stepResults'])) {
                throw new Error("Expected the field `stepResults` to be an array in the JSON data but got " + data['stepResults']);
            }
            // validate the optional field `stepResults` (array)
            for (const item of data['stepResults']) {
                AutoTestStepResult.validateJSON(item);
            };
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AttachmentApiResult.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The name of the step.
 * @member {String} title
 */
AutoTestStepResult.prototype['title'] = undefined;

/**
 * Description of the step result.
 * @member {String} description
 */
AutoTestStepResult.prototype['description'] = undefined;

/**
 * Extended description of the step result.
 * @member {String} info
 */
AutoTestStepResult.prototype['info'] = undefined;

/**
 * Step start date.
 * @member {Date} startedOn
 */
AutoTestStepResult.prototype['startedOn'] = undefined;

/**
 * Step end date.
 * @member {Date} completedOn
 */
AutoTestStepResult.prototype['completedOn'] = undefined;

/**
 * Expected or actual duration of the test run execution in milliseconds.
 * @member {Number} duration
 */
AutoTestStepResult.prototype['duration'] = undefined;

/**
 * Specifies the result of the autotest execution.
 * @member {module:model/AvailableTestResultOutcome} outcome
 */
AutoTestStepResult.prototype['outcome'] = undefined;

/**
 * Nested step results. The maximum nesting level is 15.
 * @member {Array.<module:model/AutoTestStepResult>} stepResults
 */
AutoTestStepResult.prototype['stepResults'] = undefined;

/**
 * /// <summary>  Specifies an attachment GUID. Multiple values can be sent.  </summary>
 * @member {Array.<module:model/AttachmentApiResult>} attachments
 */
AutoTestStepResult.prototype['attachments'] = undefined;

/**
 * \"<b>parameter</b>\": \"<b>value</b>\" pair with arbitrary custom parameters. Multiple parameters can be sent.
 * @member {Object.<String, String>} parameters
 */
AutoTestStepResult.prototype['parameters'] = undefined;






export default AutoTestStepResult;

