/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigurationModel model module.
 * @module model/ConfigurationModel
 * @version 1.0.0
 */
class ConfigurationModel {
    /**
     * Constructs a new <code>ConfigurationModel</code>.
     * @alias module:model/ConfigurationModel
     * @param projectId {String} This property is used to link configuration with project
     * @param isDefault {Boolean} 
     * @param createdDate {Date} 
     * @param createdById {String} 
     * @param globalId {Number} 
     * @param id {String} Unique ID of the entity
     * @param isDeleted {Boolean} Indicates if the entity is deleted
     */
    constructor(projectId, isDefault, createdDate, createdById, globalId, id, isDeleted) { 
        
        ConfigurationModel.initialize(this, projectId, isDefault, createdDate, createdById, globalId, id, isDeleted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectId, isDefault, createdDate, createdById, globalId, id, isDeleted) { 
        obj['projectId'] = projectId;
        obj['isDefault'] = isDefault;
        obj['createdDate'] = createdDate;
        obj['createdById'] = createdById;
        obj['globalId'] = globalId;
        obj['id'] = id;
        obj['isDeleted'] = isDeleted;
    }

    /**
     * Constructs a <code>ConfigurationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigurationModel} obj Optional instance to populate.
     * @return {module:model/ConfigurationModel} The populated <code>ConfigurationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigurationModel();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('modifiedDate')) {
                obj['modifiedDate'] = ApiClient.convertToType(data['modifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdById')) {
                obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
            }
            if (data.hasOwnProperty('modifiedById')) {
                obj['modifiedById'] = ApiClient.convertToType(data['modifiedById'], 'String');
            }
            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConfigurationModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConfigurationModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConfigurationModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['createdById'] && !(typeof data['createdById'] === 'string' || data['createdById'] instanceof String)) {
            throw new Error("Expected the field `createdById` to be a primitive type in the JSON string but got " + data['createdById']);
        }
        // ensure the json data is a string
        if (data['modifiedById'] && !(typeof data['modifiedById'] === 'string' || data['modifiedById'] instanceof String)) {
            throw new Error("Expected the field `modifiedById` to be a primitive type in the JSON string but got " + data['modifiedById']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

ConfigurationModel.RequiredProperties = ["projectId", "isDefault", "createdDate", "createdById", "globalId", "id", "isDeleted"];

/**
 * @member {String} description
 */
ConfigurationModel.prototype['description'] = undefined;

/**
 * @member {Object.<String, String>} parameters
 */
ConfigurationModel.prototype['parameters'] = undefined;

/**
 * This property is used to link configuration with project
 * @member {String} projectId
 */
ConfigurationModel.prototype['projectId'] = undefined;

/**
 * @member {Boolean} isDefault
 */
ConfigurationModel.prototype['isDefault'] = undefined;

/**
 * @member {String} name
 */
ConfigurationModel.prototype['name'] = undefined;

/**
 * @member {Date} createdDate
 */
ConfigurationModel.prototype['createdDate'] = undefined;

/**
 * @member {Date} modifiedDate
 */
ConfigurationModel.prototype['modifiedDate'] = undefined;

/**
 * @member {String} createdById
 */
ConfigurationModel.prototype['createdById'] = undefined;

/**
 * @member {String} modifiedById
 */
ConfigurationModel.prototype['modifiedById'] = undefined;

/**
 * @member {Number} globalId
 */
ConfigurationModel.prototype['globalId'] = undefined;

/**
 * Unique ID of the entity
 * @member {String} id
 */
ConfigurationModel.prototype['id'] = undefined;

/**
 * Indicates if the entity is deleted
 * @member {Boolean} isDeleted
 */
ConfigurationModel.prototype['isDeleted'] = undefined;






export default ConfigurationModel;

