/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignAttachmentApiModel from './AssignAttachmentApiModel';
import AssignIterationApiModel from './AssignIterationApiModel';
import AutoTestIdModel from './AutoTestIdModel';
import CreateLinkApiModel from './CreateLinkApiModel';
import CreateStepApiModel from './CreateStepApiModel';
import TagModel from './TagModel';
import WorkItemEntityTypeApiModel from './WorkItemEntityTypeApiModel';
import WorkItemParameterKeyApiModel from './WorkItemParameterKeyApiModel';
import WorkItemPriorityApiModel from './WorkItemPriorityApiModel';
import WorkItemStateApiModel from './WorkItemStateApiModel';

/**
 * The CreateWorkItemApiModel model module.
 * @module model/CreateWorkItemApiModel
 * @version 1.0.0
 */
class CreateWorkItemApiModel {
    /**
     * Constructs a new <code>CreateWorkItemApiModel</code>.
     * @alias module:model/CreateWorkItemApiModel
     * @param projectId {String} Unique identifier of the project
     * @param name {String} Name of the work item
     * @param entityTypeName {module:model/WorkItemEntityTypeApiModel} Type of entity associated with this work item
     * @param duration {Number} Duration of the work item in milliseconds
     * @param state {module:model/WorkItemStateApiModel} Current state of the work item
     * @param priority {module:model/WorkItemPriorityApiModel} Priority level assigned to the work item
     */
    constructor(projectId, name, entityTypeName, duration, state, priority) { 
        
        CreateWorkItemApiModel.initialize(this, projectId, name, entityTypeName, duration, state, priority);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectId, name, entityTypeName, duration, state, priority) { 
        obj['projectId'] = projectId;
        obj['name'] = name;
        obj['entityTypeName'] = entityTypeName;
        obj['duration'] = duration;
        obj['state'] = state;
        obj['priority'] = priority;
    }

    /**
     * Constructs a <code>CreateWorkItemApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateWorkItemApiModel} obj Optional instance to populate.
     * @return {module:model/CreateWorkItemApiModel} The populated <code>CreateWorkItemApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateWorkItemApiModel();

            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('sectionId')) {
                obj['sectionId'] = ApiClient.convertToType(data['sectionId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('entityTypeName')) {
                obj['entityTypeName'] = ApiClient.convertToType(data['entityTypeName'], WorkItemEntityTypeApiModel);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], WorkItemStateApiModel);
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], WorkItemPriorityApiModel);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': Object});
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagModel]);
            }
            if (data.hasOwnProperty('preconditionSteps')) {
                obj['preconditionSteps'] = ApiClient.convertToType(data['preconditionSteps'], [CreateStepApiModel]);
            }
            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [CreateStepApiModel]);
            }
            if (data.hasOwnProperty('postconditionSteps')) {
                obj['postconditionSteps'] = ApiClient.convertToType(data['postconditionSteps'], [CreateStepApiModel]);
            }
            if (data.hasOwnProperty('iterations')) {
                obj['iterations'] = ApiClient.convertToType(data['iterations'], [AssignIterationApiModel]);
            }
            if (data.hasOwnProperty('autoTests')) {
                obj['autoTests'] = ApiClient.convertToType(data['autoTests'], [AutoTestIdModel]);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AssignAttachmentApiModel]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [CreateLinkApiModel]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [WorkItemParameterKeyApiModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateWorkItemApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateWorkItemApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateWorkItemApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['sectionId'] && !(typeof data['sectionId'] === 'string' || data['sectionId'] instanceof String)) {
            throw new Error("Expected the field `sectionId` to be a primitive type in the JSON string but got " + data['sectionId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                TagModel.validateJSON(item);
            };
        }
        if (data['preconditionSteps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['preconditionSteps'])) {
                throw new Error("Expected the field `preconditionSteps` to be an array in the JSON data but got " + data['preconditionSteps']);
            }
            // validate the optional field `preconditionSteps` (array)
            for (const item of data['preconditionSteps']) {
                CreateStepApiModel.validateJSON(item);
            };
        }
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                CreateStepApiModel.validateJSON(item);
            };
        }
        if (data['postconditionSteps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['postconditionSteps'])) {
                throw new Error("Expected the field `postconditionSteps` to be an array in the JSON data but got " + data['postconditionSteps']);
            }
            // validate the optional field `postconditionSteps` (array)
            for (const item of data['postconditionSteps']) {
                CreateStepApiModel.validateJSON(item);
            };
        }
        if (data['iterations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['iterations'])) {
                throw new Error("Expected the field `iterations` to be an array in the JSON data but got " + data['iterations']);
            }
            // validate the optional field `iterations` (array)
            for (const item of data['iterations']) {
                AssignIterationApiModel.validateJSON(item);
            };
        }
        if (data['autoTests']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['autoTests'])) {
                throw new Error("Expected the field `autoTests` to be an array in the JSON data but got " + data['autoTests']);
            }
            // validate the optional field `autoTests` (array)
            for (const item of data['autoTests']) {
                AutoTestIdModel.validateJSON(item);
            };
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AssignAttachmentApiModel.validateJSON(item);
            };
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                CreateLinkApiModel.validateJSON(item);
            };
        }
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                WorkItemParameterKeyApiModel.validateJSON(item);
            };
        }

        return true;
    }


}

CreateWorkItemApiModel.RequiredProperties = ["projectId", "name", "entityTypeName", "duration", "state", "priority"];

/**
 * Unique identifier of the project
 * @member {String} projectId
 */
CreateWorkItemApiModel.prototype['projectId'] = undefined;

/**
 * Unique identifier of the section within a project
 * @member {String} sectionId
 */
CreateWorkItemApiModel.prototype['sectionId'] = undefined;

/**
 * Name of the work item
 * @member {String} name
 */
CreateWorkItemApiModel.prototype['name'] = undefined;

/**
 * Description of the work item
 * @member {String} description
 */
CreateWorkItemApiModel.prototype['description'] = undefined;

/**
 * Type of entity associated with this work item
 * @member {module:model/WorkItemEntityTypeApiModel} entityTypeName
 */
CreateWorkItemApiModel.prototype['entityTypeName'] = undefined;

/**
 * Duration of the work item in milliseconds
 * @member {Number} duration
 */
CreateWorkItemApiModel.prototype['duration'] = undefined;

/**
 * Current state of the work item
 * @member {module:model/WorkItemStateApiModel} state
 */
CreateWorkItemApiModel.prototype['state'] = undefined;

/**
 * Priority level assigned to the work item
 * @member {module:model/WorkItemPriorityApiModel} priority
 */
CreateWorkItemApiModel.prototype['priority'] = undefined;

/**
 * Set of custom attributes associated with the work item
 * @member {Object.<String, Object>} attributes
 */
CreateWorkItemApiModel.prototype['attributes'] = undefined;

/**
 * Set of tags applied to the work item
 * @member {Array.<module:model/TagModel>} tags
 */
CreateWorkItemApiModel.prototype['tags'] = undefined;

/**
 * Set of precondition steps that must be executed before the main steps
 * @member {Array.<module:model/CreateStepApiModel>} preconditionSteps
 */
CreateWorkItemApiModel.prototype['preconditionSteps'] = undefined;

/**
 * Set of main steps or actions defined for the work item
 * @member {Array.<module:model/CreateStepApiModel>} steps
 */
CreateWorkItemApiModel.prototype['steps'] = undefined;

/**
 * Set of postcondition steps that are executed after completing the main steps
 * @member {Array.<module:model/CreateStepApiModel>} postconditionSteps
 */
CreateWorkItemApiModel.prototype['postconditionSteps'] = undefined;

/**
 * Set of iterations associated with the work item
 * @member {Array.<module:model/AssignIterationApiModel>} iterations
 */
CreateWorkItemApiModel.prototype['iterations'] = undefined;

/**
 * Set of automated tests linked to the work item
 * @member {Array.<module:model/AutoTestIdModel>} autoTests
 */
CreateWorkItemApiModel.prototype['autoTests'] = undefined;

/**
 * Set of files attached to the work item
 * @member {Array.<module:model/AssignAttachmentApiModel>} attachments
 */
CreateWorkItemApiModel.prototype['attachments'] = undefined;

/**
 * Set of links related to the work item
 * @member {Array.<module:model/CreateLinkApiModel>} links
 */
CreateWorkItemApiModel.prototype['links'] = undefined;

/**
 * Set of parameter keys associated with the work item
 * @member {Array.<module:model/WorkItemParameterKeyApiModel>} parameters
 */
CreateWorkItemApiModel.prototype['parameters'] = undefined;






export default CreateWorkItemApiModel;

