/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomAttributeOptionModel from './CustomAttributeOptionModel';
import CustomAttributeTypesEnum from './CustomAttributeTypesEnum';

/**
 * The CustomAttributeGetModel model module.
 * @module model/CustomAttributeGetModel
 * @version 1.0.0
 */
class CustomAttributeGetModel {
    /**
     * Constructs a new <code>CustomAttributeGetModel</code>.
     * @alias module:model/CustomAttributeGetModel
     * @param id {String} Unique ID of the attribute
     * @param options {Array.<module:model/CustomAttributeOptionModel>} Collection of the attribute options
     * @param type {module:model/CustomAttributeTypesEnum} Type of the attribute
     * @param isDeleted {Boolean} Indicates if the attribute is deleted
     * @param name {String} Name of the attribute
     * @param isEnabled {Boolean} Indicates if the attribute is enabled
     * @param isRequired {Boolean} Indicates if the attribute is mandatory to specify
     * @param isGlobal {Boolean} Indicates if the attribute is available across all projects
     */
    constructor(id, options, type, isDeleted, name, isEnabled, isRequired, isGlobal) { 
        
        CustomAttributeGetModel.initialize(this, id, options, type, isDeleted, name, isEnabled, isRequired, isGlobal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, options, type, isDeleted, name, isEnabled, isRequired, isGlobal) { 
        obj['id'] = id;
        obj['options'] = options;
        obj['type'] = type;
        obj['isDeleted'] = isDeleted;
        obj['name'] = name;
        obj['isEnabled'] = isEnabled;
        obj['isRequired'] = isRequired;
        obj['isGlobal'] = isGlobal;
    }

    /**
     * Constructs a <code>CustomAttributeGetModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttributeGetModel} obj Optional instance to populate.
     * @return {module:model/CustomAttributeGetModel} The populated <code>CustomAttributeGetModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttributeGetModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [CustomAttributeOptionModel]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], CustomAttributeTypesEnum);
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('isRequired')) {
                obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('isGlobal')) {
                obj['isGlobal'] = ApiClient.convertToType(data['isGlobal'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomAttributeGetModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomAttributeGetModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomAttributeGetModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                CustomAttributeOptionModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

CustomAttributeGetModel.RequiredProperties = ["id", "options", "type", "isDeleted", "name", "isEnabled", "isRequired", "isGlobal"];

/**
 * Unique ID of the attribute
 * @member {String} id
 */
CustomAttributeGetModel.prototype['id'] = undefined;

/**
 * Collection of the attribute options
 * @member {Array.<module:model/CustomAttributeOptionModel>} options
 */
CustomAttributeGetModel.prototype['options'] = undefined;

/**
 * Type of the attribute
 * @member {module:model/CustomAttributeTypesEnum} type
 */
CustomAttributeGetModel.prototype['type'] = undefined;

/**
 * Indicates if the attribute is deleted
 * @member {Boolean} isDeleted
 */
CustomAttributeGetModel.prototype['isDeleted'] = undefined;

/**
 * Name of the attribute
 * @member {String} name
 */
CustomAttributeGetModel.prototype['name'] = undefined;

/**
 * Indicates if the attribute is enabled
 * @member {Boolean} isEnabled
 */
CustomAttributeGetModel.prototype['isEnabled'] = undefined;

/**
 * Indicates if the attribute is mandatory to specify
 * @member {Boolean} isRequired
 */
CustomAttributeGetModel.prototype['isRequired'] = undefined;

/**
 * Indicates if the attribute is available across all projects
 * @member {Boolean} isGlobal
 */
CustomAttributeGetModel.prototype['isGlobal'] = undefined;






export default CustomAttributeGetModel;

