/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomAttributeOptionModel model module.
 * @module model/CustomAttributeOptionModel
 * @version 1.0.0
 */
class CustomAttributeOptionModel {
    /**
     * Constructs a new <code>CustomAttributeOptionModel</code>.
     * @alias module:model/CustomAttributeOptionModel
     * @param id {String} Unique ID of the attribute option
     * @param isDeleted {Boolean} Indicates if the attributes option is deleted
     * @param isDefault {Boolean} Indicates if the attribute option is used by default
     */
    constructor(id, isDeleted, isDefault) { 
        
        CustomAttributeOptionModel.initialize(this, id, isDeleted, isDefault);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, isDeleted, isDefault) { 
        obj['id'] = id;
        obj['isDeleted'] = isDeleted;
        obj['isDefault'] = isDefault;
    }

    /**
     * Constructs a <code>CustomAttributeOptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttributeOptionModel} obj Optional instance to populate.
     * @return {module:model/CustomAttributeOptionModel} The populated <code>CustomAttributeOptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttributeOptionModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomAttributeOptionModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomAttributeOptionModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomAttributeOptionModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

CustomAttributeOptionModel.RequiredProperties = ["id", "isDeleted", "isDefault"];

/**
 * Unique ID of the attribute option
 * @member {String} id
 */
CustomAttributeOptionModel.prototype['id'] = undefined;

/**
 * Indicates if the attributes option is deleted
 * @member {Boolean} isDeleted
 */
CustomAttributeOptionModel.prototype['isDeleted'] = undefined;

/**
 * Value of the attribute option
 * @member {String} value
 */
CustomAttributeOptionModel.prototype['value'] = undefined;

/**
 * Indicates if the attribute option is used by default
 * @member {Boolean} isDefault
 */
CustomAttributeOptionModel.prototype['isDefault'] = undefined;






export default CustomAttributeOptionModel;

