/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FailureCategoryModel.
* @enum {}
* @readonly
*/
export default class FailureCategoryModel {
    
        /**
         * value: "InfrastructureDefect"
         * @const
         */
        "InfrastructureDefect" = "InfrastructureDefect";

    
        /**
         * value: "ProductDefect"
         * @const
         */
        "ProductDefect" = "ProductDefect";

    
        /**
         * value: "TestDefect"
         * @const
         */
        "TestDefect" = "TestDefect";

    
        /**
         * value: "NoDefect"
         * @const
         */
        "NoDefect" = "NoDefect";

    
        /**
         * value: "NoAnalytics"
         * @const
         */
        "NoAnalytics" = "NoAnalytics";

    

    /**
    * Returns a <code>FailureCategoryModel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/FailureCategoryModel} The enum <code>FailureCategoryModel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

