/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParameterShortModel from './ParameterShortModel';

/**
 * The IterationModel model module.
 * @module model/IterationModel
 * @version 1.0.0
 */
class IterationModel {
    /**
     * Constructs a new <code>IterationModel</code>.
     * @alias module:model/IterationModel
     * @param id {String} 
     */
    constructor(id) { 
        
        IterationModel.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>IterationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IterationModel} obj Optional instance to populate.
     * @return {module:model/IterationModel} The populated <code>IterationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IterationModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [ParameterShortModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IterationModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IterationModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IterationModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                ParameterShortModel.validateJSON(item);
            };
        }

        return true;
    }


}

IterationModel.RequiredProperties = ["id"];

/**
 * @member {String} id
 */
IterationModel.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/ParameterShortModel>} parameters
 */
IterationModel.prototype['parameters'] = undefined;






export default IterationModel;

