/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LinkType from './LinkType';

/**
 * The LinkPostModel model module.
 * @module model/LinkPostModel
 * @version 1.0.0
 */
class LinkPostModel {
    /**
     * Constructs a new <code>LinkPostModel</code>.
     * @alias module:model/LinkPostModel
     * @param url {String} Address can be specified without protocol, but necessarily with the domain.
     * @param type {module:model/LinkType} Specifies the type of the link.
     * @param hasInfo {Boolean} 
     */
    constructor(url, type, hasInfo) { 
        
        LinkPostModel.initialize(this, url, type, hasInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, type, hasInfo) { 
        obj['url'] = url;
        obj['type'] = type;
        obj['hasInfo'] = hasInfo;
    }

    /**
     * Constructs a <code>LinkPostModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LinkPostModel} obj Optional instance to populate.
     * @return {module:model/LinkPostModel} The populated <code>LinkPostModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LinkPostModel();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], LinkType);
            }
            if (data.hasOwnProperty('hasInfo')) {
                obj['hasInfo'] = ApiClient.convertToType(data['hasInfo'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LinkPostModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LinkPostModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LinkPostModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

LinkPostModel.RequiredProperties = ["url", "type", "hasInfo"];

/**
 * Link name.
 * @member {String} title
 */
LinkPostModel.prototype['title'] = undefined;

/**
 * Address can be specified without protocol, but necessarily with the domain.
 * @member {String} url
 */
LinkPostModel.prototype['url'] = undefined;

/**
 * Link description.
 * @member {String} description
 */
LinkPostModel.prototype['description'] = undefined;

/**
 * Specifies the type of the link.
 * @member {module:model/LinkType} type
 */
LinkPostModel.prototype['type'] = undefined;

/**
 * @member {Boolean} hasInfo
 */
LinkPostModel.prototype['hasInfo'] = undefined;






export default LinkPostModel;

