/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LinkType.
* @enum {}
* @readonly
*/
export default class LinkType {
    
        /**
         * value: "Related"
         * @const
         */
        "Related" = "Related";

    
        /**
         * value: "BlockedBy"
         * @const
         */
        "BlockedBy" = "BlockedBy";

    
        /**
         * value: "Defect"
         * @const
         */
        "Defect" = "Defect";

    
        /**
         * value: "Issue"
         * @const
         */
        "Issue" = "Issue";

    
        /**
         * value: "Requirement"
         * @const
         */
        "Requirement" = "Requirement";

    
        /**
         * value: "Repository"
         * @const
         */
        "Repository" = "Repository";

    

    /**
    * Returns a <code>LinkType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LinkType} The enum <code>LinkType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

