/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParametersFilterApiModel model module.
 * @module model/ParametersFilterApiModel
 * @version 1.0.0
 */
class ParametersFilterApiModel {
    /**
     * Constructs a new <code>ParametersFilterApiModel</code>.
     * @alias module:model/ParametersFilterApiModel
     */
    constructor() { 
        
        ParametersFilterApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParametersFilterApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParametersFilterApiModel} obj Optional instance to populate.
     * @return {module:model/ParametersFilterApiModel} The populated <code>ParametersFilterApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParametersFilterApiModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('projectIds')) {
                obj['projectIds'] = ApiClient.convertToType(data['projectIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParametersFilterApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ParametersFilterApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['projectIds'])) {
            throw new Error("Expected the field `projectIds` to be an array in the JSON data but got " + data['projectIds']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
ParametersFilterApiModel.prototype['name'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
ParametersFilterApiModel.prototype['isDeleted'] = undefined;

/**
 * @member {Array.<String>} projectIds
 */
ParametersFilterApiModel.prototype['projectIds'] = undefined;






export default ParametersFilterApiModel;

