/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowStatusApiResult from './WorkflowStatusApiResult';

/**
 * The WorkflowApiResult model module.
 * @module model/WorkflowApiResult
 * @version 1.0.0
 */
class WorkflowApiResult {
    /**
     * Constructs a new <code>WorkflowApiResult</code>.
     * @alias module:model/WorkflowApiResult
     * @param id {String} 
     * @param statuses {Array.<module:model/WorkflowStatusApiResult>} 
     */
    constructor(id, statuses) { 
        
        WorkflowApiResult.initialize(this, id, statuses);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, statuses) { 
        obj['id'] = id;
        obj['statuses'] = statuses;
    }

    /**
     * Constructs a <code>WorkflowApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowApiResult} obj Optional instance to populate.
     * @return {module:model/WorkflowApiResult} The populated <code>WorkflowApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('statuses')) {
                obj['statuses'] = ApiClient.convertToType(data['statuses'], [WorkflowStatusApiResult]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['statuses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['statuses'])) {
                throw new Error("Expected the field `statuses` to be an array in the JSON data but got " + data['statuses']);
            }
            // validate the optional field `statuses` (array)
            for (const item of data['statuses']) {
                WorkflowStatusApiResult.validateJSON(item);
            };
        }

        return true;
    }


}

WorkflowApiResult.RequiredProperties = ["id", "statuses"];

/**
 * @member {String} id
 */
WorkflowApiResult.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/WorkflowStatusApiResult>} statuses
 */
WorkflowApiResult.prototype['statuses'] = undefined;






export default WorkflowApiResult;

