/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WorkItemPriorityModel.
* @enum {}
* @readonly
*/
export default class WorkItemPriorityModel {
    
        /**
         * value: "Lowest"
         * @const
         */
        "Lowest" = "Lowest";

    
        /**
         * value: "Low"
         * @const
         */
        "Low" = "Low";

    
        /**
         * value: "Medium"
         * @const
         */
        "Medium" = "Medium";

    
        /**
         * value: "High"
         * @const
         */
        "High" = "High";

    
        /**
         * value: "Highest"
         * @const
         */
        "Highest" = "Highest";

    

    /**
    * Returns a <code>WorkItemPriorityModel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WorkItemPriorityModel} The enum <code>WorkItemPriorityModel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

