/**
 * Sync Storage Service API
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InProgressPublishedResponse model module.
 * @module model/InProgressPublishedResponse
 * @version 0.1.0
 */
class InProgressPublishedResponse {
    /**
     * Constructs a new <code>InProgressPublishedResponse</code>.
     * @alias module:model/InProgressPublishedResponse
     */
    constructor() { 
        
        InProgressPublishedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InProgressPublishedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InProgressPublishedResponse} obj Optional instance to populate.
     * @return {module:model/InProgressPublishedResponse} The populated <code>InProgressPublishedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InProgressPublishedResponse();

            if (data.hasOwnProperty('published')) {
                obj['published'] = ApiClient.convertToType(data['published'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InProgressPublishedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InProgressPublishedResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} published
 */
InProgressPublishedResponse.prototype['published'] = undefined;






export default InProgressPublishedResponse;

