/**
 * Sync Storage Service API
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InProgressPublishedResponse from '../model/InProgressPublishedResponse';
import TestResultCutApiModel from '../model/TestResultCutApiModel';
import TestResultSaveResponse from '../model/TestResultSaveResponse';

/**
* TestResults service.
* @module api/TestResultsApi
* @version 0.1.0
*/
export default class TestResultsApi {

    /**
    * Constructs a new TestResultsApi. 
    * @alias module:api/TestResultsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get in-progress published state
     *  Get whether in-progress status has already been published by master node.
     * @param {String} testRunId Test Run ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InProgressPublishedResponse} and HTTP response
     */
    inProgressPublishedGetWithHttpInfo(testRunId) {
      let postBody = null;
      // verify the required parameter 'testRunId' is set
      if (testRunId === undefined || testRunId === null) {
        throw new Error("Missing the required parameter 'testRunId' when calling inProgressPublishedGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'testRunId': testRunId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InProgressPublishedResponse;
      return this.apiClient.callApi(
        '/in_progress_published', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get in-progress published state
     *  Get whether in-progress status has already been published by master node.
     * @param {String} testRunId Test Run ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InProgressPublishedResponse}
     */
    inProgressPublishedGet(testRunId) {
      return this.inProgressPublishedGetWithHttpInfo(testRunId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Save in-progress test result
     *  Save a test result with InProgress status.
     * @param {String} testRunId Test Run ID
     * @param {module:model/TestResultCutApiModel} testResultCutApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestResultSaveResponse} and HTTP response
     */
    inProgressTestResultPostWithHttpInfo(testRunId, testResultCutApiModel) {
      let postBody = testResultCutApiModel;
      // verify the required parameter 'testRunId' is set
      if (testRunId === undefined || testRunId === null) {
        throw new Error("Missing the required parameter 'testRunId' when calling inProgressTestResultPost");
      }
      // verify the required parameter 'testResultCutApiModel' is set
      if (testResultCutApiModel === undefined || testResultCutApiModel === null) {
        throw new Error("Missing the required parameter 'testResultCutApiModel' when calling inProgressTestResultPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'testRunId': testRunId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TestResultSaveResponse;
      return this.apiClient.callApi(
        '/in_progress_test_result', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Save in-progress test result
     *  Save a test result with InProgress status.
     * @param {String} testRunId Test Run ID
     * @param {module:model/TestResultCutApiModel} testResultCutApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestResultSaveResponse}
     */
    inProgressTestResultPost(testRunId, testResultCutApiModel) {
      return this.inProgressTestResultPostWithHttpInfo(testRunId, testResultCutApiModel)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
