/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AssignAttachmentApiModel from './model/AssignAttachmentApiModel';
import AssignAutoTestCaseIdApiModel from './model/AssignAutoTestCaseIdApiModel';
import AssignIterationApiModel from './model/AssignIterationApiModel';
import AttachmentApiResult from './model/AttachmentApiResult';
import AttachmentModel from './model/AttachmentModel';
import AttachmentPutModel from './model/AttachmentPutModel';
import AttachmentPutModelAutoTestStepResultsModel from './model/AttachmentPutModelAutoTestStepResultsModel';
import AttachmentUpdateRequest from './model/AttachmentUpdateRequest';
import AutoTest from './model/AutoTest';
import AutoTestApiResult from './model/AutoTestApiResult';
import AutoTestCaseApiModel from './model/AutoTestCaseApiModel';
import AutoTestCreateApiModel from './model/AutoTestCreateApiModel';
import AutoTestFilterApiModel from './model/AutoTestFilterApiModel';
import AutoTestIdModel from './model/AutoTestIdModel';
import AutoTestModel from './model/AutoTestModel';
import AutoTestResultReasonShort from './model/AutoTestResultReasonShort';
import AutoTestResultsForTestRunModel from './model/AutoTestResultsForTestRunModel';
import AutoTestSearchApiModel from './model/AutoTestSearchApiModel';
import AutoTestSearchIncludeApiModel from './model/AutoTestSearchIncludeApiModel';
import AutoTestStep from './model/AutoTestStep';
import AutoTestStepApiModel from './model/AutoTestStepApiModel';
import AutoTestStepApiResult from './model/AutoTestStepApiResult';
import AutoTestStepModel from './model/AutoTestStepModel';
import AutoTestStepResult from './model/AutoTestStepResult';
import AutoTestStepResultUpdateRequest from './model/AutoTestStepResultUpdateRequest';
import AutoTestUpdateApiModel from './model/AutoTestUpdateApiModel';
import AutoTestWorkItemIdentifierApiResult from './model/AutoTestWorkItemIdentifierApiResult';
import AvailableTestResultOutcome from './model/AvailableTestResultOutcome';
import ConfigurationFilterModel from './model/ConfigurationFilterModel';
import ConfigurationModel from './model/ConfigurationModel';
import ConfigurationShortModel from './model/ConfigurationShortModel';
import CreateEmptyTestRunApiModel from './model/CreateEmptyTestRunApiModel';
import CreateLinkApiModel from './model/CreateLinkApiModel';
import CreateParameterApiModel from './model/CreateParameterApiModel';
import CreateProjectApiModel from './model/CreateProjectApiModel';
import CreateStepApiModel from './model/CreateStepApiModel';
import CreateWorkItemApiModel from './model/CreateWorkItemApiModel';
import CustomAttributeApiResult from './model/CustomAttributeApiResult';
import CustomAttributeGetModel from './model/CustomAttributeGetModel';
import CustomAttributeOptionApiResult from './model/CustomAttributeOptionApiResult';
import CustomAttributeOptionModel from './model/CustomAttributeOptionModel';
import CustomAttributePutModel from './model/CustomAttributePutModel';
import CustomAttributeType from './model/CustomAttributeType';
import CustomAttributeTypesEnum from './model/CustomAttributeTypesEnum';
import DateTimeRangeSelectorModel from './model/DateTimeRangeSelectorModel';
import DeletionState from './model/DeletionState';
import DetailedProjectApiResult from './model/DetailedProjectApiResult';
import FailureCategoryModel from './model/FailureCategoryModel';
import GuidExtractionModel from './model/GuidExtractionModel';
import ImageResizeType from './model/ImageResizeType';
import Int32RangeSelectorModel from './model/Int32RangeSelectorModel';
import Int64RangeSelectorModel from './model/Int64RangeSelectorModel';
import IterationApiResult from './model/IterationApiResult';
import IterationModel from './model/IterationModel';
import LabelApiModel from './model/LabelApiModel';
import LabelApiResult from './model/LabelApiResult';
import LabelShortModel from './model/LabelShortModel';
import LinkApiResult from './model/LinkApiResult';
import LinkCreateApiModel from './model/LinkCreateApiModel';
import LinkModel from './model/LinkModel';
import LinkPostModel from './model/LinkPostModel';
import LinkPutModel from './model/LinkPutModel';
import LinkShortApiResult from './model/LinkShortApiResult';
import LinkType from './model/LinkType';
import LinkUpdateApiModel from './model/LinkUpdateApiModel';
import ManualRerunApiResult from './model/ManualRerunApiResult';
import ManualRerunSelectTestResultsApiModel from './model/ManualRerunSelectTestResultsApiModel';
import ManualRerunTestResultApiModel from './model/ManualRerunTestResultApiModel';
import Operation from './model/Operation';
import ParameterApiResult from './model/ParameterApiResult';
import ParameterIterationModel from './model/ParameterIterationModel';
import ParameterShortApiResult from './model/ParameterShortApiResult';
import ParameterShortModel from './model/ParameterShortModel';
import ParametersFilterApiModel from './model/ParametersFilterApiModel';
import ProblemDetails from './model/ProblemDetails';
import ProjectApiResult from './model/ProjectApiResult';
import ProjectAttributesFilterModel from './model/ProjectAttributesFilterModel';
import ProjectTypeModel from './model/ProjectTypeModel';
import ProjectsFilterModel from './model/ProjectsFilterModel';
import SectionModel from './model/SectionModel';
import SectionPostModel from './model/SectionPostModel';
import SectionWithStepsModel from './model/SectionWithStepsModel';
import SharedStepModel from './model/SharedStepModel';
import SharedStepResultApiModel from './model/SharedStepResultApiModel';
import StepCommentApiModel from './model/StepCommentApiModel';
import StepModel from './model/StepModel';
import StepPostModel from './model/StepPostModel';
import StepResultApiModel from './model/StepResultApiModel';
import TagModel from './model/TagModel';
import TestResultLinkApiResult from './model/TestResultLinkApiResult';
import TestResultOutcome from './model/TestResultOutcome';
import TestResultResponse from './model/TestResultResponse';
import TestResultShortResponse from './model/TestResultShortResponse';
import TestResultStepCommentUpdateRequest from './model/TestResultStepCommentUpdateRequest';
import TestResultUpdateRequest from './model/TestResultUpdateRequest';
import TestResultsFilterApiModel from './model/TestResultsFilterApiModel';
import TestRunApiResult from './model/TestRunApiResult';
import TestRunState from './model/TestRunState';
import TestStatusApiResult from './model/TestStatusApiResult';
import TestStatusApiType from './model/TestStatusApiType';
import TestStatusModel from './model/TestStatusModel';
import TestStatusType from './model/TestStatusType';
import UpdateEmptyTestRunApiModel from './model/UpdateEmptyTestRunApiModel';
import UpdateLinkApiModel from './model/UpdateLinkApiModel';
import ValidationProblemDetails from './model/ValidationProblemDetails';
import WorkItemApiResult from './model/WorkItemApiResult';
import WorkItemEntityTypeApiModel from './model/WorkItemEntityTypeApiModel';
import WorkItemFilterApiModel from './model/WorkItemFilterApiModel';
import WorkItemIdApiModel from './model/WorkItemIdApiModel';
import WorkItemParameterKeyApiModel from './model/WorkItemParameterKeyApiModel';
import WorkItemParameterKeyApiResult from './model/WorkItemParameterKeyApiResult';
import WorkItemPriorityApiModel from './model/WorkItemPriorityApiModel';
import WorkItemPriorityModel from './model/WorkItemPriorityModel';
import WorkItemSelectApiModel from './model/WorkItemSelectApiModel';
import WorkItemShortApiResult from './model/WorkItemShortApiResult';
import WorkItemSourceTypeModel from './model/WorkItemSourceTypeModel';
import WorkItemStateApiModel from './model/WorkItemStateApiModel';
import WorkItemStates from './model/WorkItemStates';
import WorkItemTypeModel from './model/WorkItemTypeModel';
import WorkflowApiResult from './model/WorkflowApiResult';
import WorkflowStatusApiResult from './model/WorkflowStatusApiResult';
import AttachmentsApi from './api/AttachmentsApi';
import AutoTestsApi from './api/AutoTestsApi';
import ConfigurationsApi from './api/ConfigurationsApi';
import ParametersApi from './api/ParametersApi';
import ProjectAttributesApi from './api/ProjectAttributesApi';
import ProjectSectionsApi from './api/ProjectSectionsApi';
import ProjectWorkItemsApi from './api/ProjectWorkItemsApi';
import ProjectsApi from './api/ProjectsApi';
import SectionsApi from './api/SectionsApi';
import TestResultsApi from './api/TestResultsApi';
import TestRunsApi from './api/TestRunsApi';
import WorkItemsApi from './api/WorkItemsApi';
import WorkflowsApi from './api/WorkflowsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AdaptersApi = require('index'); // See note below*.
* var xxxSvc = new AdaptersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AdaptersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AdaptersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AdaptersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssignAttachmentApiModel model constructor.
     * @property {module:model/AssignAttachmentApiModel}
     */
    AssignAttachmentApiModel,

    /**
     * The AssignAutoTestCaseIdApiModel model constructor.
     * @property {module:model/AssignAutoTestCaseIdApiModel}
     */
    AssignAutoTestCaseIdApiModel,

    /**
     * The AssignIterationApiModel model constructor.
     * @property {module:model/AssignIterationApiModel}
     */
    AssignIterationApiModel,

    /**
     * The AttachmentApiResult model constructor.
     * @property {module:model/AttachmentApiResult}
     */
    AttachmentApiResult,

    /**
     * The AttachmentModel model constructor.
     * @property {module:model/AttachmentModel}
     */
    AttachmentModel,

    /**
     * The AttachmentPutModel model constructor.
     * @property {module:model/AttachmentPutModel}
     */
    AttachmentPutModel,

    /**
     * The AttachmentPutModelAutoTestStepResultsModel model constructor.
     * @property {module:model/AttachmentPutModelAutoTestStepResultsModel}
     */
    AttachmentPutModelAutoTestStepResultsModel,

    /**
     * The AttachmentUpdateRequest model constructor.
     * @property {module:model/AttachmentUpdateRequest}
     */
    AttachmentUpdateRequest,

    /**
     * The AutoTest model constructor.
     * @property {module:model/AutoTest}
     */
    AutoTest,

    /**
     * The AutoTestApiResult model constructor.
     * @property {module:model/AutoTestApiResult}
     */
    AutoTestApiResult,

    /**
     * The AutoTestCaseApiModel model constructor.
     * @property {module:model/AutoTestCaseApiModel}
     */
    AutoTestCaseApiModel,

    /**
     * The AutoTestCreateApiModel model constructor.
     * @property {module:model/AutoTestCreateApiModel}
     */
    AutoTestCreateApiModel,

    /**
     * The AutoTestFilterApiModel model constructor.
     * @property {module:model/AutoTestFilterApiModel}
     */
    AutoTestFilterApiModel,

    /**
     * The AutoTestIdModel model constructor.
     * @property {module:model/AutoTestIdModel}
     */
    AutoTestIdModel,

    /**
     * The AutoTestModel model constructor.
     * @property {module:model/AutoTestModel}
     */
    AutoTestModel,

    /**
     * The AutoTestResultReasonShort model constructor.
     * @property {module:model/AutoTestResultReasonShort}
     */
    AutoTestResultReasonShort,

    /**
     * The AutoTestResultsForTestRunModel model constructor.
     * @property {module:model/AutoTestResultsForTestRunModel}
     */
    AutoTestResultsForTestRunModel,

    /**
     * The AutoTestSearchApiModel model constructor.
     * @property {module:model/AutoTestSearchApiModel}
     */
    AutoTestSearchApiModel,

    /**
     * The AutoTestSearchIncludeApiModel model constructor.
     * @property {module:model/AutoTestSearchIncludeApiModel}
     */
    AutoTestSearchIncludeApiModel,

    /**
     * The AutoTestStep model constructor.
     * @property {module:model/AutoTestStep}
     */
    AutoTestStep,

    /**
     * The AutoTestStepApiModel model constructor.
     * @property {module:model/AutoTestStepApiModel}
     */
    AutoTestStepApiModel,

    /**
     * The AutoTestStepApiResult model constructor.
     * @property {module:model/AutoTestStepApiResult}
     */
    AutoTestStepApiResult,

    /**
     * The AutoTestStepModel model constructor.
     * @property {module:model/AutoTestStepModel}
     */
    AutoTestStepModel,

    /**
     * The AutoTestStepResult model constructor.
     * @property {module:model/AutoTestStepResult}
     */
    AutoTestStepResult,

    /**
     * The AutoTestStepResultUpdateRequest model constructor.
     * @property {module:model/AutoTestStepResultUpdateRequest}
     */
    AutoTestStepResultUpdateRequest,

    /**
     * The AutoTestUpdateApiModel model constructor.
     * @property {module:model/AutoTestUpdateApiModel}
     */
    AutoTestUpdateApiModel,

    /**
     * The AutoTestWorkItemIdentifierApiResult model constructor.
     * @property {module:model/AutoTestWorkItemIdentifierApiResult}
     */
    AutoTestWorkItemIdentifierApiResult,

    /**
     * The AvailableTestResultOutcome model constructor.
     * @property {module:model/AvailableTestResultOutcome}
     */
    AvailableTestResultOutcome,

    /**
     * The ConfigurationFilterModel model constructor.
     * @property {module:model/ConfigurationFilterModel}
     */
    ConfigurationFilterModel,

    /**
     * The ConfigurationModel model constructor.
     * @property {module:model/ConfigurationModel}
     */
    ConfigurationModel,

    /**
     * The ConfigurationShortModel model constructor.
     * @property {module:model/ConfigurationShortModel}
     */
    ConfigurationShortModel,

    /**
     * The CreateEmptyTestRunApiModel model constructor.
     * @property {module:model/CreateEmptyTestRunApiModel}
     */
    CreateEmptyTestRunApiModel,

    /**
     * The CreateLinkApiModel model constructor.
     * @property {module:model/CreateLinkApiModel}
     */
    CreateLinkApiModel,

    /**
     * The CreateParameterApiModel model constructor.
     * @property {module:model/CreateParameterApiModel}
     */
    CreateParameterApiModel,

    /**
     * The CreateProjectApiModel model constructor.
     * @property {module:model/CreateProjectApiModel}
     */
    CreateProjectApiModel,

    /**
     * The CreateStepApiModel model constructor.
     * @property {module:model/CreateStepApiModel}
     */
    CreateStepApiModel,

    /**
     * The CreateWorkItemApiModel model constructor.
     * @property {module:model/CreateWorkItemApiModel}
     */
    CreateWorkItemApiModel,

    /**
     * The CustomAttributeApiResult model constructor.
     * @property {module:model/CustomAttributeApiResult}
     */
    CustomAttributeApiResult,

    /**
     * The CustomAttributeGetModel model constructor.
     * @property {module:model/CustomAttributeGetModel}
     */
    CustomAttributeGetModel,

    /**
     * The CustomAttributeOptionApiResult model constructor.
     * @property {module:model/CustomAttributeOptionApiResult}
     */
    CustomAttributeOptionApiResult,

    /**
     * The CustomAttributeOptionModel model constructor.
     * @property {module:model/CustomAttributeOptionModel}
     */
    CustomAttributeOptionModel,

    /**
     * The CustomAttributePutModel model constructor.
     * @property {module:model/CustomAttributePutModel}
     */
    CustomAttributePutModel,

    /**
     * The CustomAttributeType model constructor.
     * @property {module:model/CustomAttributeType}
     */
    CustomAttributeType,

    /**
     * The CustomAttributeTypesEnum model constructor.
     * @property {module:model/CustomAttributeTypesEnum}
     */
    CustomAttributeTypesEnum,

    /**
     * The DateTimeRangeSelectorModel model constructor.
     * @property {module:model/DateTimeRangeSelectorModel}
     */
    DateTimeRangeSelectorModel,

    /**
     * The DeletionState model constructor.
     * @property {module:model/DeletionState}
     */
    DeletionState,

    /**
     * The DetailedProjectApiResult model constructor.
     * @property {module:model/DetailedProjectApiResult}
     */
    DetailedProjectApiResult,

    /**
     * The FailureCategoryModel model constructor.
     * @property {module:model/FailureCategoryModel}
     */
    FailureCategoryModel,

    /**
     * The GuidExtractionModel model constructor.
     * @property {module:model/GuidExtractionModel}
     */
    GuidExtractionModel,

    /**
     * The ImageResizeType model constructor.
     * @property {module:model/ImageResizeType}
     */
    ImageResizeType,

    /**
     * The Int32RangeSelectorModel model constructor.
     * @property {module:model/Int32RangeSelectorModel}
     */
    Int32RangeSelectorModel,

    /**
     * The Int64RangeSelectorModel model constructor.
     * @property {module:model/Int64RangeSelectorModel}
     */
    Int64RangeSelectorModel,

    /**
     * The IterationApiResult model constructor.
     * @property {module:model/IterationApiResult}
     */
    IterationApiResult,

    /**
     * The IterationModel model constructor.
     * @property {module:model/IterationModel}
     */
    IterationModel,

    /**
     * The LabelApiModel model constructor.
     * @property {module:model/LabelApiModel}
     */
    LabelApiModel,

    /**
     * The LabelApiResult model constructor.
     * @property {module:model/LabelApiResult}
     */
    LabelApiResult,

    /**
     * The LabelShortModel model constructor.
     * @property {module:model/LabelShortModel}
     */
    LabelShortModel,

    /**
     * The LinkApiResult model constructor.
     * @property {module:model/LinkApiResult}
     */
    LinkApiResult,

    /**
     * The LinkCreateApiModel model constructor.
     * @property {module:model/LinkCreateApiModel}
     */
    LinkCreateApiModel,

    /**
     * The LinkModel model constructor.
     * @property {module:model/LinkModel}
     */
    LinkModel,

    /**
     * The LinkPostModel model constructor.
     * @property {module:model/LinkPostModel}
     */
    LinkPostModel,

    /**
     * The LinkPutModel model constructor.
     * @property {module:model/LinkPutModel}
     */
    LinkPutModel,

    /**
     * The LinkShortApiResult model constructor.
     * @property {module:model/LinkShortApiResult}
     */
    LinkShortApiResult,

    /**
     * The LinkType model constructor.
     * @property {module:model/LinkType}
     */
    LinkType,

    /**
     * The LinkUpdateApiModel model constructor.
     * @property {module:model/LinkUpdateApiModel}
     */
    LinkUpdateApiModel,

    /**
     * The ManualRerunApiResult model constructor.
     * @property {module:model/ManualRerunApiResult}
     */
    ManualRerunApiResult,

    /**
     * The ManualRerunSelectTestResultsApiModel model constructor.
     * @property {module:model/ManualRerunSelectTestResultsApiModel}
     */
    ManualRerunSelectTestResultsApiModel,

    /**
     * The ManualRerunTestResultApiModel model constructor.
     * @property {module:model/ManualRerunTestResultApiModel}
     */
    ManualRerunTestResultApiModel,

    /**
     * The Operation model constructor.
     * @property {module:model/Operation}
     */
    Operation,

    /**
     * The ParameterApiResult model constructor.
     * @property {module:model/ParameterApiResult}
     */
    ParameterApiResult,

    /**
     * The ParameterIterationModel model constructor.
     * @property {module:model/ParameterIterationModel}
     */
    ParameterIterationModel,

    /**
     * The ParameterShortApiResult model constructor.
     * @property {module:model/ParameterShortApiResult}
     */
    ParameterShortApiResult,

    /**
     * The ParameterShortModel model constructor.
     * @property {module:model/ParameterShortModel}
     */
    ParameterShortModel,

    /**
     * The ParametersFilterApiModel model constructor.
     * @property {module:model/ParametersFilterApiModel}
     */
    ParametersFilterApiModel,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The ProjectApiResult model constructor.
     * @property {module:model/ProjectApiResult}
     */
    ProjectApiResult,

    /**
     * The ProjectAttributesFilterModel model constructor.
     * @property {module:model/ProjectAttributesFilterModel}
     */
    ProjectAttributesFilterModel,

    /**
     * The ProjectTypeModel model constructor.
     * @property {module:model/ProjectTypeModel}
     */
    ProjectTypeModel,

    /**
     * The ProjectsFilterModel model constructor.
     * @property {module:model/ProjectsFilterModel}
     */
    ProjectsFilterModel,

    /**
     * The SectionModel model constructor.
     * @property {module:model/SectionModel}
     */
    SectionModel,

    /**
     * The SectionPostModel model constructor.
     * @property {module:model/SectionPostModel}
     */
    SectionPostModel,

    /**
     * The SectionWithStepsModel model constructor.
     * @property {module:model/SectionWithStepsModel}
     */
    SectionWithStepsModel,

    /**
     * The SharedStepModel model constructor.
     * @property {module:model/SharedStepModel}
     */
    SharedStepModel,

    /**
     * The SharedStepResultApiModel model constructor.
     * @property {module:model/SharedStepResultApiModel}
     */
    SharedStepResultApiModel,

    /**
     * The StepCommentApiModel model constructor.
     * @property {module:model/StepCommentApiModel}
     */
    StepCommentApiModel,

    /**
     * The StepModel model constructor.
     * @property {module:model/StepModel}
     */
    StepModel,

    /**
     * The StepPostModel model constructor.
     * @property {module:model/StepPostModel}
     */
    StepPostModel,

    /**
     * The StepResultApiModel model constructor.
     * @property {module:model/StepResultApiModel}
     */
    StepResultApiModel,

    /**
     * The TagModel model constructor.
     * @property {module:model/TagModel}
     */
    TagModel,

    /**
     * The TestResultLinkApiResult model constructor.
     * @property {module:model/TestResultLinkApiResult}
     */
    TestResultLinkApiResult,

    /**
     * The TestResultOutcome model constructor.
     * @property {module:model/TestResultOutcome}
     */
    TestResultOutcome,

    /**
     * The TestResultResponse model constructor.
     * @property {module:model/TestResultResponse}
     */
    TestResultResponse,

    /**
     * The TestResultShortResponse model constructor.
     * @property {module:model/TestResultShortResponse}
     */
    TestResultShortResponse,

    /**
     * The TestResultStepCommentUpdateRequest model constructor.
     * @property {module:model/TestResultStepCommentUpdateRequest}
     */
    TestResultStepCommentUpdateRequest,

    /**
     * The TestResultUpdateRequest model constructor.
     * @property {module:model/TestResultUpdateRequest}
     */
    TestResultUpdateRequest,

    /**
     * The TestResultsFilterApiModel model constructor.
     * @property {module:model/TestResultsFilterApiModel}
     */
    TestResultsFilterApiModel,

    /**
     * The TestRunApiResult model constructor.
     * @property {module:model/TestRunApiResult}
     */
    TestRunApiResult,

    /**
     * The TestRunState model constructor.
     * @property {module:model/TestRunState}
     */
    TestRunState,

    /**
     * The TestStatusApiResult model constructor.
     * @property {module:model/TestStatusApiResult}
     */
    TestStatusApiResult,

    /**
     * The TestStatusApiType model constructor.
     * @property {module:model/TestStatusApiType}
     */
    TestStatusApiType,

    /**
     * The TestStatusModel model constructor.
     * @property {module:model/TestStatusModel}
     */
    TestStatusModel,

    /**
     * The TestStatusType model constructor.
     * @property {module:model/TestStatusType}
     */
    TestStatusType,

    /**
     * The UpdateEmptyTestRunApiModel model constructor.
     * @property {module:model/UpdateEmptyTestRunApiModel}
     */
    UpdateEmptyTestRunApiModel,

    /**
     * The UpdateLinkApiModel model constructor.
     * @property {module:model/UpdateLinkApiModel}
     */
    UpdateLinkApiModel,

    /**
     * The ValidationProblemDetails model constructor.
     * @property {module:model/ValidationProblemDetails}
     */
    ValidationProblemDetails,

    /**
     * The WorkItemApiResult model constructor.
     * @property {module:model/WorkItemApiResult}
     */
    WorkItemApiResult,

    /**
     * The WorkItemEntityTypeApiModel model constructor.
     * @property {module:model/WorkItemEntityTypeApiModel}
     */
    WorkItemEntityTypeApiModel,

    /**
     * The WorkItemFilterApiModel model constructor.
     * @property {module:model/WorkItemFilterApiModel}
     */
    WorkItemFilterApiModel,

    /**
     * The WorkItemIdApiModel model constructor.
     * @property {module:model/WorkItemIdApiModel}
     */
    WorkItemIdApiModel,

    /**
     * The WorkItemParameterKeyApiModel model constructor.
     * @property {module:model/WorkItemParameterKeyApiModel}
     */
    WorkItemParameterKeyApiModel,

    /**
     * The WorkItemParameterKeyApiResult model constructor.
     * @property {module:model/WorkItemParameterKeyApiResult}
     */
    WorkItemParameterKeyApiResult,

    /**
     * The WorkItemPriorityApiModel model constructor.
     * @property {module:model/WorkItemPriorityApiModel}
     */
    WorkItemPriorityApiModel,

    /**
     * The WorkItemPriorityModel model constructor.
     * @property {module:model/WorkItemPriorityModel}
     */
    WorkItemPriorityModel,

    /**
     * The WorkItemSelectApiModel model constructor.
     * @property {module:model/WorkItemSelectApiModel}
     */
    WorkItemSelectApiModel,

    /**
     * The WorkItemShortApiResult model constructor.
     * @property {module:model/WorkItemShortApiResult}
     */
    WorkItemShortApiResult,

    /**
     * The WorkItemSourceTypeModel model constructor.
     * @property {module:model/WorkItemSourceTypeModel}
     */
    WorkItemSourceTypeModel,

    /**
     * The WorkItemStateApiModel model constructor.
     * @property {module:model/WorkItemStateApiModel}
     */
    WorkItemStateApiModel,

    /**
     * The WorkItemStates model constructor.
     * @property {module:model/WorkItemStates}
     */
    WorkItemStates,

    /**
     * The WorkItemTypeModel model constructor.
     * @property {module:model/WorkItemTypeModel}
     */
    WorkItemTypeModel,

    /**
     * The WorkflowApiResult model constructor.
     * @property {module:model/WorkflowApiResult}
     */
    WorkflowApiResult,

    /**
     * The WorkflowStatusApiResult model constructor.
     * @property {module:model/WorkflowStatusApiResult}
     */
    WorkflowStatusApiResult,

    /**
    * The AttachmentsApi service constructor.
    * @property {module:api/AttachmentsApi}
    */
    AttachmentsApi,

    /**
    * The AutoTestsApi service constructor.
    * @property {module:api/AutoTestsApi}
    */
    AutoTestsApi,

    /**
    * The ConfigurationsApi service constructor.
    * @property {module:api/ConfigurationsApi}
    */
    ConfigurationsApi,

    /**
    * The ParametersApi service constructor.
    * @property {module:api/ParametersApi}
    */
    ParametersApi,

    /**
    * The ProjectAttributesApi service constructor.
    * @property {module:api/ProjectAttributesApi}
    */
    ProjectAttributesApi,

    /**
    * The ProjectSectionsApi service constructor.
    * @property {module:api/ProjectSectionsApi}
    */
    ProjectSectionsApi,

    /**
    * The ProjectWorkItemsApi service constructor.
    * @property {module:api/ProjectWorkItemsApi}
    */
    ProjectWorkItemsApi,

    /**
    * The ProjectsApi service constructor.
    * @property {module:api/ProjectsApi}
    */
    ProjectsApi,

    /**
    * The SectionsApi service constructor.
    * @property {module:api/SectionsApi}
    */
    SectionsApi,

    /**
    * The TestResultsApi service constructor.
    * @property {module:api/TestResultsApi}
    */
    TestResultsApi,

    /**
    * The TestRunsApi service constructor.
    * @property {module:api/TestRunsApi}
    */
    TestRunsApi,

    /**
    * The WorkItemsApi service constructor.
    * @property {module:api/WorkItemsApi}
    */
    WorkItemsApi,

    /**
    * The WorkflowsApi service constructor.
    * @property {module:api/WorkflowsApi}
    */
    WorkflowsApi
};
