/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssignAutoTestCaseIdApiModel model module.
 * @module model/AssignAutoTestCaseIdApiModel
 * @version 1.0.0
 */
class AssignAutoTestCaseIdApiModel {
    /**
     * Constructs a new <code>AssignAutoTestCaseIdApiModel</code>.
     * @alias module:model/AssignAutoTestCaseIdApiModel
     * @param id {String} Unique ID of the automated test case
     */
    constructor(id) { 
        
        AssignAutoTestCaseIdApiModel.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>AssignAutoTestCaseIdApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssignAutoTestCaseIdApiModel} obj Optional instance to populate.
     * @return {module:model/AssignAutoTestCaseIdApiModel} The populated <code>AssignAutoTestCaseIdApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssignAutoTestCaseIdApiModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssignAutoTestCaseIdApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssignAutoTestCaseIdApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssignAutoTestCaseIdApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

AssignAutoTestCaseIdApiModel.RequiredProperties = ["id"];

/**
 * Unique ID of the automated test case
 * @member {String} id
 */
AssignAutoTestCaseIdApiModel.prototype['id'] = undefined;






export default AssignAutoTestCaseIdApiModel;

