/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AttachmentApiResult model module.
 * @module model/AttachmentApiResult
 * @version 1.0.0
 */
class AttachmentApiResult {
    /**
     * Constructs a new <code>AttachmentApiResult</code>.
     * @alias module:model/AttachmentApiResult
     * @param id {String} Unique ID of the attachment
     * @param fileId {String} Unique ID of the attachment file
     * @param type {String} MIME type of the attachment
     * @param size {Number} Size in bytes of the attachment file
     * @param name {String} Name of the attachment file
     */
    constructor(id, fileId, type, size, name) { 
        
        AttachmentApiResult.initialize(this, id, fileId, type, size, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, fileId, type, size, name) { 
        obj['id'] = id;
        obj['fileId'] = fileId;
        obj['type'] = type;
        obj['size'] = size;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>AttachmentApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttachmentApiResult} obj Optional instance to populate.
     * @return {module:model/AttachmentApiResult} The populated <code>AttachmentApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttachmentApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('fileId')) {
                obj['fileId'] = ApiClient.convertToType(data['fileId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AttachmentApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AttachmentApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AttachmentApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['fileId'] && !(typeof data['fileId'] === 'string' || data['fileId'] instanceof String)) {
            throw new Error("Expected the field `fileId` to be a primitive type in the JSON string but got " + data['fileId']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

AttachmentApiResult.RequiredProperties = ["id", "fileId", "type", "size", "name"];

/**
 * Unique ID of the attachment
 * @member {String} id
 */
AttachmentApiResult.prototype['id'] = undefined;

/**
 * Unique ID of the attachment file
 * @member {String} fileId
 */
AttachmentApiResult.prototype['fileId'] = undefined;

/**
 * MIME type of the attachment
 * @member {String} type
 */
AttachmentApiResult.prototype['type'] = undefined;

/**
 * Size in bytes of the attachment file
 * @member {Number} size
 */
AttachmentApiResult.prototype['size'] = undefined;

/**
 * Name of the attachment file
 * @member {String} name
 */
AttachmentApiResult.prototype['name'] = undefined;






export default AttachmentApiResult;

