/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoTestStep from './AutoTestStep';
import LabelApiModel from './LabelApiModel';
import LinkApiResult from './LinkApiResult';

/**
 * The AutoTest model module.
 * @module model/AutoTest
 * @version 1.0.0
 */
class AutoTest {
    /**
     * Constructs a new <code>AutoTest</code>.
     * @alias module:model/AutoTest
     * @param externalId {String} External ID of the autotest
     * @param projectId {String} Unique ID of the autotest project
     * @param name {String} Name of the autotest
     * @param globalId {Number} Global ID of the autotest
     * @param id {String} Unique ID of the autotest
     */
    constructor(externalId, projectId, name, globalId, id) { 
        
        AutoTest.initialize(this, externalId, projectId, name, globalId, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, externalId, projectId, name, globalId, id) { 
        obj['externalId'] = externalId;
        obj['projectId'] = projectId;
        obj['name'] = name;
        obj['globalId'] = globalId;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>AutoTest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoTest} obj Optional instance to populate.
     * @return {module:model/AutoTest} The populated <code>AutoTest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoTest();

            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LinkApiResult]);
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('classname')) {
                obj['classname'] = ApiClient.convertToType(data['classname'], 'String');
            }
            if (data.hasOwnProperty('steps')) {
                obj['steps'] = ApiClient.convertToType(data['steps'], [AutoTestStep]);
            }
            if (data.hasOwnProperty('setup')) {
                obj['setup'] = ApiClient.convertToType(data['setup'], [AutoTestStep]);
            }
            if (data.hasOwnProperty('teardown')) {
                obj['teardown'] = ApiClient.convertToType(data['teardown'], [AutoTestStep]);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], [LabelApiModel]);
            }
            if (data.hasOwnProperty('isFlaky')) {
                obj['isFlaky'] = ApiClient.convertToType(data['isFlaky'], 'Boolean');
            }
            if (data.hasOwnProperty('externalKey')) {
                obj['externalKey'] = ApiClient.convertToType(data['externalKey'], 'String');
            }
            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoTest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoTest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AutoTest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['externalId'] && !(typeof data['externalId'] === 'string' || data['externalId'] instanceof String)) {
            throw new Error("Expected the field `externalId` to be a primitive type in the JSON string but got " + data['externalId']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LinkApiResult.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['namespace'] && !(typeof data['namespace'] === 'string' || data['namespace'] instanceof String)) {
            throw new Error("Expected the field `namespace` to be a primitive type in the JSON string but got " + data['namespace']);
        }
        // ensure the json data is a string
        if (data['classname'] && !(typeof data['classname'] === 'string' || data['classname'] instanceof String)) {
            throw new Error("Expected the field `classname` to be a primitive type in the JSON string but got " + data['classname']);
        }
        if (data['steps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['steps'])) {
                throw new Error("Expected the field `steps` to be an array in the JSON data but got " + data['steps']);
            }
            // validate the optional field `steps` (array)
            for (const item of data['steps']) {
                AutoTestStep.validateJSON(item);
            };
        }
        if (data['setup']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['setup'])) {
                throw new Error("Expected the field `setup` to be an array in the JSON data but got " + data['setup']);
            }
            // validate the optional field `setup` (array)
            for (const item of data['setup']) {
                AutoTestStep.validateJSON(item);
            };
        }
        if (data['teardown']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teardown'])) {
                throw new Error("Expected the field `teardown` to be an array in the JSON data but got " + data['teardown']);
            }
            // validate the optional field `teardown` (array)
            for (const item of data['teardown']) {
                AutoTestStep.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['labels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['labels'])) {
                throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
            }
            // validate the optional field `labels` (array)
            for (const item of data['labels']) {
                LabelApiModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['externalKey'] && !(typeof data['externalKey'] === 'string' || data['externalKey'] instanceof String)) {
            throw new Error("Expected the field `externalKey` to be a primitive type in the JSON string but got " + data['externalKey']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

AutoTest.RequiredProperties = ["externalId", "projectId", "name", "globalId", "id"];

/**
 * External ID of the autotest
 * @member {String} externalId
 */
AutoTest.prototype['externalId'] = undefined;

/**
 * Collection of the autotest links
 * @member {Array.<module:model/LinkApiResult>} links
 */
AutoTest.prototype['links'] = undefined;

/**
 * Unique ID of the autotest project
 * @member {String} projectId
 */
AutoTest.prototype['projectId'] = undefined;

/**
 * Name of the autotest
 * @member {String} name
 */
AutoTest.prototype['name'] = undefined;

/**
 * Name of the autotest namespace
 * @member {String} namespace
 */
AutoTest.prototype['namespace'] = undefined;

/**
 * Name of the autotest class
 * @member {String} classname
 */
AutoTest.prototype['classname'] = undefined;

/**
 * Collection of the autotest steps
 * @member {Array.<module:model/AutoTestStep>} steps
 */
AutoTest.prototype['steps'] = undefined;

/**
 * Collection of the autotest setup steps
 * @member {Array.<module:model/AutoTestStep>} setup
 */
AutoTest.prototype['setup'] = undefined;

/**
 * Collection of the autotest teardown steps
 * @member {Array.<module:model/AutoTestStep>} teardown
 */
AutoTest.prototype['teardown'] = undefined;

/**
 * Name of the autotest in autotest's card
 * @member {String} title
 */
AutoTest.prototype['title'] = undefined;

/**
 * Description of the autotest in autotest's card
 * @member {String} description
 */
AutoTest.prototype['description'] = undefined;

/**
 * Collection of the autotest labels
 * @member {Array.<module:model/LabelApiModel>} labels
 */
AutoTest.prototype['labels'] = undefined;

/**
 * Indicates if the autotest is marked as flaky
 * @member {Boolean} isFlaky
 */
AutoTest.prototype['isFlaky'] = undefined;

/**
 * External key of the autotest
 * @member {String} externalKey
 */
AutoTest.prototype['externalKey'] = undefined;

/**
 * Global ID of the autotest
 * @member {Number} globalId
 */
AutoTest.prototype['globalId'] = undefined;

/**
 * Unique ID of the autotest
 * @member {String} id
 */
AutoTest.prototype['id'] = undefined;






export default AutoTest;

