/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CustomAttributeTypesEnum.
* @enum {}
* @readonly
*/
export default class CustomAttributeTypesEnum {
    
        /**
         * value: "string"
         * @const
         */
        "string" = "string";

    
        /**
         * value: "datetime"
         * @const
         */
        "datetime" = "datetime";

    
        /**
         * value: "options"
         * @const
         */
        "options" = "options";

    
        /**
         * value: "user"
         * @const
         */
        "user" = "user";

    
        /**
         * value: "multipleOptions"
         * @const
         */
        "multipleOptions" = "multipleOptions";

    
        /**
         * value: "checkbox"
         * @const
         */
        "checkbox" = "checkbox";

    

    /**
    * Returns a <code>CustomAttributeTypesEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CustomAttributeTypesEnum} The enum <code>CustomAttributeTypesEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

