/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomAttributeOptionPostApiModel model module.
 * @module model/CustomAttributeOptionPostApiModel
 * @version 1.0.0
 */
class CustomAttributeOptionPostApiModel {
    /**
     * Constructs a new <code>CustomAttributeOptionPostApiModel</code>.
     * @alias module:model/CustomAttributeOptionPostApiModel
     * @param isDefault {Boolean} Indicates if the attribute option is used by default
     */
    constructor(isDefault) { 
        
        CustomAttributeOptionPostApiModel.initialize(this, isDefault);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isDefault) { 
        obj['isDefault'] = isDefault;
    }

    /**
     * Constructs a <code>CustomAttributeOptionPostApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttributeOptionPostApiModel} obj Optional instance to populate.
     * @return {module:model/CustomAttributeOptionPostApiModel} The populated <code>CustomAttributeOptionPostApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttributeOptionPostApiModel();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomAttributeOptionPostApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomAttributeOptionPostApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomAttributeOptionPostApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

CustomAttributeOptionPostApiModel.RequiredProperties = ["isDefault"];

/**
 * Value of the attribute option
 * @member {String} value
 */
CustomAttributeOptionPostApiModel.prototype['value'] = undefined;

/**
 * Indicates if the attribute option is used by default
 * @member {Boolean} isDefault
 */
CustomAttributeOptionPostApiModel.prototype['isDefault'] = undefined;






export default CustomAttributeOptionPostApiModel;

