/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomAttributeType from './CustomAttributeType';

/**
 * The CustomAttributeSearchApiModel model module.
 * @module model/CustomAttributeSearchApiModel
 * @version 1.0.0
 */
class CustomAttributeSearchApiModel {
    /**
     * Constructs a new <code>CustomAttributeSearchApiModel</code>.
     * @alias module:model/CustomAttributeSearchApiModel
     */
    constructor() { 
        
        CustomAttributeSearchApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomAttributeSearchApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttributeSearchApiModel} obj Optional instance to populate.
     * @return {module:model/CustomAttributeSearchApiModel} The populated <code>CustomAttributeSearchApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttributeSearchApiModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('projectIds')) {
                obj['projectIds'] = ApiClient.convertToType(data['projectIds'], ['String']);
            }
            if (data.hasOwnProperty('customAttributeIds')) {
                obj['customAttributeIds'] = ApiClient.convertToType(data['customAttributeIds'], ['String']);
            }
            if (data.hasOwnProperty('customAttributeTypes')) {
                obj['customAttributeTypes'] = ApiClient.convertToType(data['customAttributeTypes'], [CustomAttributeType]);
            }
            if (data.hasOwnProperty('isGlobal')) {
                obj['isGlobal'] = ApiClient.convertToType(data['isGlobal'], 'Boolean');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomAttributeSearchApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomAttributeSearchApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['projectIds'])) {
            throw new Error("Expected the field `projectIds` to be an array in the JSON data but got " + data['projectIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['customAttributeIds'])) {
            throw new Error("Expected the field `customAttributeIds` to be an array in the JSON data but got " + data['customAttributeIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['customAttributeTypes'])) {
            throw new Error("Expected the field `customAttributeTypes` to be an array in the JSON data but got " + data['customAttributeTypes']);
        }

        return true;
    }


}



/**
 * Name of attribute
 * @member {String} name
 */
CustomAttributeSearchApiModel.prototype['name'] = undefined;

/**
 * Unique IDs of projects where attribute is in use
 * @member {Array.<String>} projectIds
 */
CustomAttributeSearchApiModel.prototype['projectIds'] = undefined;

/**
 * Unique IDs of attributes for search restriction
 * @member {Array.<String>} customAttributeIds
 */
CustomAttributeSearchApiModel.prototype['customAttributeIds'] = undefined;

/**
 * Collection of attribute types
 * @member {Array.<module:model/CustomAttributeType>} customAttributeTypes
 */
CustomAttributeSearchApiModel.prototype['customAttributeTypes'] = undefined;

/**
 * Indicates whether the attribute is available across all projects
 * @member {Boolean} isGlobal
 */
CustomAttributeSearchApiModel.prototype['isGlobal'] = undefined;

/**
 * Indicates whether the attribute is deleted
 * @member {Boolean} isDeleted
 */
CustomAttributeSearchApiModel.prototype['isDeleted'] = undefined;






export default CustomAttributeSearchApiModel;

