/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomAttributeApiResult from './CustomAttributeApiResult';
import WorkflowApiResult from './WorkflowApiResult';

/**
 * The DetailedProjectApiResult model module.
 * @module model/DetailedProjectApiResult
 * @version 1.0.0
 */
class DetailedProjectApiResult {
    /**
     * Constructs a new <code>DetailedProjectApiResult</code>.
     * @alias module:model/DetailedProjectApiResult
     * @param workflow {module:model/WorkflowApiResult} ID of the workflow used in project
     * @param id {String} Unique ID of the project
     * @param name {String} Name of the project
     * @param isFavorite {Boolean} Indicates if the project is marked as favorite
     * @param isDeleted {Boolean} Indicates if the project is deleted
     * @param globalId {Number} Global ID of the project
     * @param workflowId {String} ID of the workflow used in project
     */
    constructor(workflow, id, name, isFavorite, isDeleted, globalId, workflowId) { 
        
        DetailedProjectApiResult.initialize(this, workflow, id, name, isFavorite, isDeleted, globalId, workflowId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workflow, id, name, isFavorite, isDeleted, globalId, workflowId) { 
        obj['workflow'] = workflow;
        obj['id'] = id;
        obj['name'] = name;
        obj['isFavorite'] = isFavorite;
        obj['isDeleted'] = isDeleted;
        obj['globalId'] = globalId;
        obj['workflowId'] = workflowId;
    }

    /**
     * Constructs a <code>DetailedProjectApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetailedProjectApiResult} obj Optional instance to populate.
     * @return {module:model/DetailedProjectApiResult} The populated <code>DetailedProjectApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetailedProjectApiResult();

            if (data.hasOwnProperty('attributesScheme')) {
                obj['attributesScheme'] = ApiClient.convertToType(data['attributesScheme'], [CustomAttributeApiResult]);
            }
            if (data.hasOwnProperty('workflow')) {
                obj['workflow'] = ApiClient.convertToType(data['workflow'], WorkflowApiResult);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isFavorite')) {
                obj['isFavorite'] = ApiClient.convertToType(data['isFavorite'], 'Boolean');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
            if (data.hasOwnProperty('workflowId')) {
                obj['workflowId'] = ApiClient.convertToType(data['workflowId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DetailedProjectApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DetailedProjectApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DetailedProjectApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['attributesScheme']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attributesScheme'])) {
                throw new Error("Expected the field `attributesScheme` to be an array in the JSON data but got " + data['attributesScheme']);
            }
            // validate the optional field `attributesScheme` (array)
            for (const item of data['attributesScheme']) {
                CustomAttributeApiResult.validateJSON(item);
            };
        }
        // validate the optional field `workflow`
        if (data['workflow']) { // data not null
          WorkflowApiResult.validateJSON(data['workflow']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['workflowId'] && !(typeof data['workflowId'] === 'string' || data['workflowId'] instanceof String)) {
            throw new Error("Expected the field `workflowId` to be a primitive type in the JSON string but got " + data['workflowId']);
        }

        return true;
    }


}

DetailedProjectApiResult.RequiredProperties = ["workflow", "id", "name", "isFavorite", "isDeleted", "globalId", "workflowId"];

/**
 * Collection of the project attributes
 * @member {Array.<module:model/CustomAttributeApiResult>} attributesScheme
 */
DetailedProjectApiResult.prototype['attributesScheme'] = undefined;

/**
 * ID of the workflow used in project
 * @member {module:model/WorkflowApiResult} workflow
 */
DetailedProjectApiResult.prototype['workflow'] = undefined;

/**
 * Unique ID of the project
 * @member {String} id
 */
DetailedProjectApiResult.prototype['id'] = undefined;

/**
 * Description of the project
 * @member {String} description
 */
DetailedProjectApiResult.prototype['description'] = undefined;

/**
 * Name of the project
 * @member {String} name
 */
DetailedProjectApiResult.prototype['name'] = undefined;

/**
 * Indicates if the project is marked as favorite
 * @member {Boolean} isFavorite
 */
DetailedProjectApiResult.prototype['isFavorite'] = undefined;

/**
 * Indicates if the project is deleted
 * @member {Boolean} isDeleted
 */
DetailedProjectApiResult.prototype['isDeleted'] = undefined;

/**
 * Global ID of the project
 * @member {Number} globalId
 */
DetailedProjectApiResult.prototype['globalId'] = undefined;

/**
 * ID of the workflow used in project
 * @member {String} workflowId
 */
DetailedProjectApiResult.prototype['workflowId'] = undefined;






export default DetailedProjectApiResult;

