/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GuidExtractionModel model module.
 * @module model/GuidExtractionModel
 * @version 1.0.0
 */
class GuidExtractionModel {
    /**
     * Constructs a new <code>GuidExtractionModel</code>.
     * @alias module:model/GuidExtractionModel
     */
    constructor() { 
        
        GuidExtractionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GuidExtractionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GuidExtractionModel} obj Optional instance to populate.
     * @return {module:model/GuidExtractionModel} The populated <code>GuidExtractionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GuidExtractionModel();

            if (data.hasOwnProperty('include')) {
                obj['include'] = ApiClient.convertToType(data['include'], ['String']);
            }
            if (data.hasOwnProperty('exclude')) {
                obj['exclude'] = ApiClient.convertToType(data['exclude'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GuidExtractionModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GuidExtractionModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['include'])) {
            throw new Error("Expected the field `include` to be an array in the JSON data but got " + data['include']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['exclude'])) {
            throw new Error("Expected the field `exclude` to be an array in the JSON data but got " + data['exclude']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} include
 */
GuidExtractionModel.prototype['include'] = undefined;

/**
 * @member {Array.<String>} exclude
 */
GuidExtractionModel.prototype['exclude'] = undefined;






export default GuidExtractionModel;

