/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ImageResizeType.
* @enum {}
* @readonly
*/
export default class ImageResizeType {
    
        /**
         * value: "Crop"
         * @const
         */
        "Crop" = "Crop";

    
        /**
         * value: "AddBackgroundStripes"
         * @const
         */
        "AddBackgroundStripes" = "AddBackgroundStripes";

    

    /**
    * Returns a <code>ImageResizeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ImageResizeType} The enum <code>ImageResizeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

