/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Int64RangeSelectorModel model module.
 * @module model/Int64RangeSelectorModel
 * @version 1.0.0
 */
class Int64RangeSelectorModel {
    /**
     * Constructs a new <code>Int64RangeSelectorModel</code>.
     * @alias module:model/Int64RangeSelectorModel
     */
    constructor() { 
        
        Int64RangeSelectorModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Int64RangeSelectorModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Int64RangeSelectorModel} obj Optional instance to populate.
     * @return {module:model/Int64RangeSelectorModel} The populated <code>Int64RangeSelectorModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Int64RangeSelectorModel();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Number');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Int64RangeSelectorModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Int64RangeSelectorModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} from
 */
Int64RangeSelectorModel.prototype['from'] = undefined;

/**
 * @member {Number} to
 */
Int64RangeSelectorModel.prototype['to'] = undefined;






export default Int64RangeSelectorModel;

