/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabelApiModel model module.
 * @module model/LabelApiModel
 * @version 1.0.0
 */
class LabelApiModel {
    /**
     * Constructs a new <code>LabelApiModel</code>.
     * @alias module:model/LabelApiModel
     * @param name {String} Name of the label
     * @param globalId {Number} Global ID of the label
     */
    constructor(name, globalId) { 
        
        LabelApiModel.initialize(this, name, globalId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, globalId) { 
        obj['name'] = name;
        obj['globalId'] = globalId;
    }

    /**
     * Constructs a <code>LabelApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LabelApiModel} obj Optional instance to populate.
     * @return {module:model/LabelApiModel} The populated <code>LabelApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabelApiModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LabelApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LabelApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LabelApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

LabelApiModel.RequiredProperties = ["name", "globalId"];

/**
 * Name of the label
 * @member {String} name
 */
LabelApiModel.prototype['name'] = undefined;

/**
 * Global ID of the label
 * @member {Number} globalId
 */
LabelApiModel.prototype['globalId'] = undefined;






export default LabelApiModel;

