/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LayerSource.
* @enum {}
* @readonly
*/
export default class LayerSource {
    
        /**
         * value: "Manual"
         * @const
         */
        "Manual" = "Manual";

    
        /**
         * value: "Report"
         * @const
         */
        "Report" = "Report";

    
        /**
         * value: "Run"
         * @const
         */
        "Run" = "Run";

    
        /**
         * value: "Rule"
         * @const
         */
        "Rule" = "Rule";

    

    /**
    * Returns a <code>LayerSource</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LayerSource} The enum <code>LayerSource</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

