/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ManualRerunApiResult model module.
 * @module model/ManualRerunApiResult
 * @version 1.0.0
 */
class ManualRerunApiResult {
    /**
     * Constructs a new <code>ManualRerunApiResult</code>.
     * @alias module:model/ManualRerunApiResult
     * @param testResultsCount {Number} 
     */
    constructor(testResultsCount) { 
        
        ManualRerunApiResult.initialize(this, testResultsCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, testResultsCount) { 
        obj['testResultsCount'] = testResultsCount;
    }

    /**
     * Constructs a <code>ManualRerunApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManualRerunApiResult} obj Optional instance to populate.
     * @return {module:model/ManualRerunApiResult} The populated <code>ManualRerunApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManualRerunApiResult();

            if (data.hasOwnProperty('testResultsCount')) {
                obj['testResultsCount'] = ApiClient.convertToType(data['testResultsCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManualRerunApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ManualRerunApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ManualRerunApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ManualRerunApiResult.RequiredProperties = ["testResultsCount"];

/**
 * @member {Number} testResultsCount
 */
ManualRerunApiResult.prototype['testResultsCount'] = undefined;






export default ManualRerunApiResult;

