/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuidExtractionModel from './GuidExtractionModel';

/**
 * The ManualRerunTestResultApiModel model module.
 * @module model/ManualRerunTestResultApiModel
 * @version 1.0.0
 */
class ManualRerunTestResultApiModel {
    /**
     * Constructs a new <code>ManualRerunTestResultApiModel</code>.
     * @alias module:model/ManualRerunTestResultApiModel
     */
    constructor() { 
        
        ManualRerunTestResultApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ManualRerunTestResultApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManualRerunTestResultApiModel} obj Optional instance to populate.
     * @return {module:model/ManualRerunTestResultApiModel} The populated <code>ManualRerunTestResultApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManualRerunTestResultApiModel();

            if (data.hasOwnProperty('testResultIds')) {
                obj['testResultIds'] = ApiClient.convertToType(data['testResultIds'], GuidExtractionModel);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManualRerunTestResultApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ManualRerunTestResultApiModel</code>.
     */
    static validateJSON(data) {
        // validate the optional field `testResultIds`
        if (data['testResultIds']) { // data not null
          GuidExtractionModel.validateJSON(data['testResultIds']);
        }

        return true;
    }


}



/**
 * Set of extracted test result IDs
 * @member {module:model/GuidExtractionModel} testResultIds
 */
ManualRerunTestResultApiModel.prototype['testResultIds'] = undefined;






export default ManualRerunTestResultApiModel;

