/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParameterApiResult model module.
 * @module model/ParameterApiResult
 * @version 1.0.0
 */
class ParameterApiResult {
    /**
     * Constructs a new <code>ParameterApiResult</code>.
     * @alias module:model/ParameterApiResult
     * @param id {String} 
     * @param parameterKeyId {String} 
     * @param name {String} 
     * @param value {String} 
     * @param isDeleted {Boolean} 
     * @param projectIds {Array.<String>} 
     */
    constructor(id, parameterKeyId, name, value, isDeleted, projectIds) { 
        
        ParameterApiResult.initialize(this, id, parameterKeyId, name, value, isDeleted, projectIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, parameterKeyId, name, value, isDeleted, projectIds) { 
        obj['id'] = id;
        obj['parameterKeyId'] = parameterKeyId;
        obj['name'] = name;
        obj['value'] = value;
        obj['isDeleted'] = isDeleted;
        obj['projectIds'] = projectIds;
    }

    /**
     * Constructs a <code>ParameterApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterApiResult} obj Optional instance to populate.
     * @return {module:model/ParameterApiResult} The populated <code>ParameterApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parameterKeyId')) {
                obj['parameterKeyId'] = ApiClient.convertToType(data['parameterKeyId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('projectIds')) {
                obj['projectIds'] = ApiClient.convertToType(data['projectIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParameterApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ParameterApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ParameterApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['parameterKeyId'] && !(typeof data['parameterKeyId'] === 'string' || data['parameterKeyId'] instanceof String)) {
            throw new Error("Expected the field `parameterKeyId` to be a primitive type in the JSON string but got " + data['parameterKeyId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['projectIds'])) {
            throw new Error("Expected the field `projectIds` to be an array in the JSON data but got " + data['projectIds']);
        }

        return true;
    }


}

ParameterApiResult.RequiredProperties = ["id", "parameterKeyId", "name", "value", "isDeleted", "projectIds"];

/**
 * @member {String} id
 */
ParameterApiResult.prototype['id'] = undefined;

/**
 * @member {String} parameterKeyId
 */
ParameterApiResult.prototype['parameterKeyId'] = undefined;

/**
 * @member {String} name
 */
ParameterApiResult.prototype['name'] = undefined;

/**
 * @member {String} value
 */
ParameterApiResult.prototype['value'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
ParameterApiResult.prototype['isDeleted'] = undefined;

/**
 * @member {Array.<String>} projectIds
 */
ParameterApiResult.prototype['projectIds'] = undefined;






export default ParameterApiResult;

