/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParameterShortApiResult model module.
 * @module model/ParameterShortApiResult
 * @version 1.0.0
 */
class ParameterShortApiResult {
    /**
     * Constructs a new <code>ParameterShortApiResult</code>.
     * @alias module:model/ParameterShortApiResult
     * @param id {String} 
     * @param parameterKeyId {String} 
     * @param value {String} Value of the parameter
     * @param name {String} Key of the parameter
     */
    constructor(id, parameterKeyId, value, name) { 
        
        ParameterShortApiResult.initialize(this, id, parameterKeyId, value, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, parameterKeyId, value, name) { 
        obj['id'] = id;
        obj['parameterKeyId'] = parameterKeyId;
        obj['value'] = value;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ParameterShortApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterShortApiResult} obj Optional instance to populate.
     * @return {module:model/ParameterShortApiResult} The populated <code>ParameterShortApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterShortApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parameterKeyId')) {
                obj['parameterKeyId'] = ApiClient.convertToType(data['parameterKeyId'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParameterShortApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ParameterShortApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ParameterShortApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['parameterKeyId'] && !(typeof data['parameterKeyId'] === 'string' || data['parameterKeyId'] instanceof String)) {
            throw new Error("Expected the field `parameterKeyId` to be a primitive type in the JSON string but got " + data['parameterKeyId']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ParameterShortApiResult.RequiredProperties = ["id", "parameterKeyId", "value", "name"];

/**
 * @member {String} id
 */
ParameterShortApiResult.prototype['id'] = undefined;

/**
 * @member {String} parameterKeyId
 */
ParameterShortApiResult.prototype['parameterKeyId'] = undefined;

/**
 * Value of the parameter
 * @member {String} value
 */
ParameterShortApiResult.prototype['value'] = undefined;

/**
 * Key of the parameter
 * @member {String} name
 */
ParameterShortApiResult.prototype['name'] = undefined;






export default ParameterShortApiResult;

