/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttachmentPutModel from './AttachmentPutModel';
import StepPostModel from './StepPostModel';

/**
 * The SectionPostModel model module.
 * @module model/SectionPostModel
 * @version 1.0.0
 */
class SectionPostModel {
    /**
     * Constructs a new <code>SectionPostModel</code>.
     * @alias module:model/SectionPostModel
     * @param name {String} 
     * @param projectId {String} 
     * @param attachments {Array.<module:model/AttachmentPutModel>} 
     */
    constructor(name, projectId, attachments) { 
        
        SectionPostModel.initialize(this, name, projectId, attachments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, projectId, attachments) { 
        obj['name'] = name;
        obj['projectId'] = projectId;
        obj['attachments'] = attachments;
    }

    /**
     * Constructs a <code>SectionPostModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SectionPostModel} obj Optional instance to populate.
     * @return {module:model/SectionPostModel} The populated <code>SectionPostModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SectionPostModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('preconditionSteps')) {
                obj['preconditionSteps'] = ApiClient.convertToType(data['preconditionSteps'], [StepPostModel]);
            }
            if (data.hasOwnProperty('postconditionSteps')) {
                obj['postconditionSteps'] = ApiClient.convertToType(data['postconditionSteps'], [StepPostModel]);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AttachmentPutModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SectionPostModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SectionPostModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SectionPostModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        if (data['preconditionSteps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['preconditionSteps'])) {
                throw new Error("Expected the field `preconditionSteps` to be an array in the JSON data but got " + data['preconditionSteps']);
            }
            // validate the optional field `preconditionSteps` (array)
            for (const item of data['preconditionSteps']) {
                StepPostModel.validateJSON(item);
            };
        }
        if (data['postconditionSteps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['postconditionSteps'])) {
                throw new Error("Expected the field `postconditionSteps` to be an array in the JSON data but got " + data['postconditionSteps']);
            }
            // validate the optional field `postconditionSteps` (array)
            for (const item of data['postconditionSteps']) {
                StepPostModel.validateJSON(item);
            };
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AttachmentPutModel.validateJSON(item);
            };
        }

        return true;
    }


}

SectionPostModel.RequiredProperties = ["name", "projectId", "attachments"];

/**
 * @member {String} name
 */
SectionPostModel.prototype['name'] = undefined;

/**
 * @member {String} projectId
 */
SectionPostModel.prototype['projectId'] = undefined;

/**
 * @member {String} parentId
 */
SectionPostModel.prototype['parentId'] = undefined;

/**
 * @member {Array.<module:model/StepPostModel>} preconditionSteps
 */
SectionPostModel.prototype['preconditionSteps'] = undefined;

/**
 * @member {Array.<module:model/StepPostModel>} postconditionSteps
 */
SectionPostModel.prototype['postconditionSteps'] = undefined;

/**
 * @member {Array.<module:model/AttachmentPutModel>} attachments
 */
SectionPostModel.prototype['attachments'] = undefined;






export default SectionPostModel;

