/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SharedStepResultApiModel from './SharedStepResultApiModel';
import StepCommentApiModel from './StepCommentApiModel';

/**
 * The StepResultApiModel model module.
 * @module model/StepResultApiModel
 * @version 1.0.0
 */
class StepResultApiModel {
    /**
     * Constructs a new <code>StepResultApiModel</code>.
     * @alias module:model/StepResultApiModel
     * @param stepId {String} 
     * @param outcome {String} 
     */
    constructor(stepId, outcome) { 
        
        StepResultApiModel.initialize(this, stepId, outcome);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stepId, outcome) { 
        obj['stepId'] = stepId;
        obj['outcome'] = outcome;
    }

    /**
     * Constructs a <code>StepResultApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StepResultApiModel} obj Optional instance to populate.
     * @return {module:model/StepResultApiModel} The populated <code>StepResultApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StepResultApiModel();

            if (data.hasOwnProperty('stepId')) {
                obj['stepId'] = ApiClient.convertToType(data['stepId'], 'String');
            }
            if (data.hasOwnProperty('outcome')) {
                obj['outcome'] = ApiClient.convertToType(data['outcome'], 'String');
            }
            if (data.hasOwnProperty('sharedStepVersionId')) {
                obj['sharedStepVersionId'] = ApiClient.convertToType(data['sharedStepVersionId'], 'String');
            }
            if (data.hasOwnProperty('sharedStepResults')) {
                obj['sharedStepResults'] = ApiClient.convertToType(data['sharedStepResults'], [SharedStepResultApiModel]);
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], StepCommentApiModel);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StepResultApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StepResultApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StepResultApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['stepId'] && !(typeof data['stepId'] === 'string' || data['stepId'] instanceof String)) {
            throw new Error("Expected the field `stepId` to be a primitive type in the JSON string but got " + data['stepId']);
        }
        // ensure the json data is a string
        if (data['outcome'] && !(typeof data['outcome'] === 'string' || data['outcome'] instanceof String)) {
            throw new Error("Expected the field `outcome` to be a primitive type in the JSON string but got " + data['outcome']);
        }
        // ensure the json data is a string
        if (data['sharedStepVersionId'] && !(typeof data['sharedStepVersionId'] === 'string' || data['sharedStepVersionId'] instanceof String)) {
            throw new Error("Expected the field `sharedStepVersionId` to be a primitive type in the JSON string but got " + data['sharedStepVersionId']);
        }
        if (data['sharedStepResults']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sharedStepResults'])) {
                throw new Error("Expected the field `sharedStepResults` to be an array in the JSON data but got " + data['sharedStepResults']);
            }
            // validate the optional field `sharedStepResults` (array)
            for (const item of data['sharedStepResults']) {
                SharedStepResultApiModel.validateJSON(item);
            };
        }
        // validate the optional field `comment`
        if (data['comment']) { // data not null
          StepCommentApiModel.validateJSON(data['comment']);
        }

        return true;
    }


}

StepResultApiModel.RequiredProperties = ["stepId", "outcome"];

/**
 * @member {String} stepId
 */
StepResultApiModel.prototype['stepId'] = undefined;

/**
 * @member {String} outcome
 */
StepResultApiModel.prototype['outcome'] = undefined;

/**
 * @member {String} sharedStepVersionId
 */
StepResultApiModel.prototype['sharedStepVersionId'] = undefined;

/**
 * @member {Array.<module:model/SharedStepResultApiModel>} sharedStepResults
 */
StepResultApiModel.prototype['sharedStepResults'] = undefined;

/**
 * @member {module:model/StepCommentApiModel} comment
 */
StepResultApiModel.prototype['comment'] = undefined;






export default StepResultApiModel;

