/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StepPostModel model module.
 * @module model/StepPostModel
 * @version 1.0.0
 */
class StepPostModel {
    /**
     * Constructs a new <code>StepPostModel</code>.
     * @alias module:model/StepPostModel
     */
    constructor() { 
        
        StepPostModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StepPostModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StepPostModel} obj Optional instance to populate.
     * @return {module:model/StepPostModel} The populated <code>StepPostModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StepPostModel();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('expected')) {
                obj['expected'] = ApiClient.convertToType(data['expected'], 'String');
            }
            if (data.hasOwnProperty('testData')) {
                obj['testData'] = ApiClient.convertToType(data['testData'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('workItemId')) {
                obj['workItemId'] = ApiClient.convertToType(data['workItemId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StepPostModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StepPostModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // ensure the json data is a string
        if (data['expected'] && !(typeof data['expected'] === 'string' || data['expected'] instanceof String)) {
            throw new Error("Expected the field `expected` to be a primitive type in the JSON string but got " + data['expected']);
        }
        // ensure the json data is a string
        if (data['testData'] && !(typeof data['testData'] === 'string' || data['testData'] instanceof String)) {
            throw new Error("Expected the field `testData` to be a primitive type in the JSON string but got " + data['testData']);
        }
        // ensure the json data is a string
        if (data['comments'] && !(typeof data['comments'] === 'string' || data['comments'] instanceof String)) {
            throw new Error("Expected the field `comments` to be a primitive type in the JSON string but got " + data['comments']);
        }
        // ensure the json data is a string
        if (data['workItemId'] && !(typeof data['workItemId'] === 'string' || data['workItemId'] instanceof String)) {
            throw new Error("Expected the field `workItemId` to be a primitive type in the JSON string but got " + data['workItemId']);
        }

        return true;
    }


}



/**
 * @member {String} action
 */
StepPostModel.prototype['action'] = undefined;

/**
 * @member {String} expected
 */
StepPostModel.prototype['expected'] = undefined;

/**
 * @member {String} testData
 */
StepPostModel.prototype['testData'] = undefined;

/**
 * @member {String} comments
 */
StepPostModel.prototype['comments'] = undefined;

/**
 * @member {String} workItemId
 */
StepPostModel.prototype['workItemId'] = undefined;






export default StepPostModel;

