/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SharedStepModel from './SharedStepModel';

/**
 * The StepModel model module.
 * @module model/StepModel
 * @version 1.0.0
 */
class StepModel {
    /**
     * Constructs a new <code>StepModel</code>.
     * @alias module:model/StepModel
     * @param id {String} 
     */
    constructor(id) { 
        
        StepModel.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>StepModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StepModel} obj Optional instance to populate.
     * @return {module:model/StepModel} The populated <code>StepModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StepModel();

            if (data.hasOwnProperty('workItem')) {
                obj['workItem'] = ApiClient.convertToType(data['workItem'], SharedStepModel);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('expected')) {
                obj['expected'] = ApiClient.convertToType(data['expected'], 'String');
            }
            if (data.hasOwnProperty('testData')) {
                obj['testData'] = ApiClient.convertToType(data['testData'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('workItemId')) {
                obj['workItemId'] = ApiClient.convertToType(data['workItemId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StepModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StepModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StepModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `workItem`
        if (data['workItem']) { // data not null
          SharedStepModel.validateJSON(data['workItem']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // ensure the json data is a string
        if (data['expected'] && !(typeof data['expected'] === 'string' || data['expected'] instanceof String)) {
            throw new Error("Expected the field `expected` to be a primitive type in the JSON string but got " + data['expected']);
        }
        // ensure the json data is a string
        if (data['testData'] && !(typeof data['testData'] === 'string' || data['testData'] instanceof String)) {
            throw new Error("Expected the field `testData` to be a primitive type in the JSON string but got " + data['testData']);
        }
        // ensure the json data is a string
        if (data['comments'] && !(typeof data['comments'] === 'string' || data['comments'] instanceof String)) {
            throw new Error("Expected the field `comments` to be a primitive type in the JSON string but got " + data['comments']);
        }
        // ensure the json data is a string
        if (data['workItemId'] && !(typeof data['workItemId'] === 'string' || data['workItemId'] instanceof String)) {
            throw new Error("Expected the field `workItemId` to be a primitive type in the JSON string but got " + data['workItemId']);
        }

        return true;
    }


}

StepModel.RequiredProperties = ["id"];

/**
 * Nested shared steps are allowed
 * @member {module:model/SharedStepModel} workItem
 */
StepModel.prototype['workItem'] = undefined;

/**
 * @member {String} id
 */
StepModel.prototype['id'] = undefined;

/**
 * @member {String} action
 */
StepModel.prototype['action'] = undefined;

/**
 * @member {String} expected
 */
StepModel.prototype['expected'] = undefined;

/**
 * @member {String} testData
 */
StepModel.prototype['testData'] = undefined;

/**
 * @member {String} comments
 */
StepModel.prototype['comments'] = undefined;

/**
 * @member {String} workItemId
 */
StepModel.prototype['workItemId'] = undefined;






export default StepModel;

