/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttachmentApiResult from './AttachmentApiResult';
import LinkApiResult from './LinkApiResult';
import TestRunState from './TestRunState';
import TestStatusApiResult from './TestStatusApiResult';

/**
 * The TestRunApiResult model module.
 * @module model/TestRunApiResult
 * @version 1.0.0
 */
class TestRunApiResult {
    /**
     * Constructs a new <code>TestRunApiResult</code>.
     * @alias module:model/TestRunApiResult
     * @param id {String} Test run unique identifier
     * @param name {String} Test run name
     * @param projectId {String} Project unique identifier              This property is used to link test run with project.
     * @param stateName {module:model/TestRunState} Test run state
     * @param status {module:model/TestStatusApiResult} Test run status
     * @param attachments {Array.<module:model/AttachmentApiResult>} Collection of attachments related to the test run
     * @param links {Array.<module:model/LinkApiResult>} Collection of links related to the test run
     * @param tags {Array.<String>} Collection of tags associated with the test run
     */
    constructor(id, name, projectId, stateName, status, attachments, links, tags) { 
        
        TestRunApiResult.initialize(this, id, name, projectId, stateName, status, attachments, links, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, projectId, stateName, status, attachments, links, tags) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['projectId'] = projectId;
        obj['stateName'] = stateName;
        obj['status'] = status;
        obj['attachments'] = attachments;
        obj['links'] = links;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>TestRunApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestRunApiResult} obj Optional instance to populate.
     * @return {module:model/TestRunApiResult} The populated <code>TestRunApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestRunApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('launchSource')) {
                obj['launchSource'] = ApiClient.convertToType(data['launchSource'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('stateName')) {
                obj['stateName'] = ApiClient.convertToType(data['stateName'], TestRunState);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], TestStatusApiResult);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AttachmentApiResult]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LinkApiResult]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestRunApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestRunApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestRunApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['launchSource'] && !(typeof data['launchSource'] === 'string' || data['launchSource'] instanceof String)) {
            throw new Error("Expected the field `launchSource` to be a primitive type in the JSON string but got " + data['launchSource']);
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          TestStatusApiResult.validateJSON(data['status']);
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AttachmentApiResult.validateJSON(item);
            };
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LinkApiResult.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

TestRunApiResult.RequiredProperties = ["id", "name", "projectId", "stateName", "status", "attachments", "links", "tags"];

/**
 * Test run unique identifier
 * @member {String} id
 */
TestRunApiResult.prototype['id'] = undefined;

/**
 * Test run name
 * @member {String} name
 */
TestRunApiResult.prototype['name'] = undefined;

/**
 * Test run description
 * @member {String} description
 */
TestRunApiResult.prototype['description'] = undefined;

/**
 * Test run launch source              Once launch source is specified it cannot be updated.
 * @member {String} launchSource
 */
TestRunApiResult.prototype['launchSource'] = undefined;

/**
 * Project unique identifier              This property is used to link test run with project.
 * @member {String} projectId
 */
TestRunApiResult.prototype['projectId'] = undefined;

/**
 * Test run state
 * @member {module:model/TestRunState} stateName
 */
TestRunApiResult.prototype['stateName'] = undefined;

/**
 * Test run status
 * @member {module:model/TestStatusApiResult} status
 */
TestRunApiResult.prototype['status'] = undefined;

/**
 * Collection of attachments related to the test run
 * @member {Array.<module:model/AttachmentApiResult>} attachments
 */
TestRunApiResult.prototype['attachments'] = undefined;

/**
 * Collection of links related to the test run
 * @member {Array.<module:model/LinkApiResult>} links
 */
TestRunApiResult.prototype['links'] = undefined;

/**
 * Collection of tags associated with the test run
 * @member {Array.<String>} tags
 */
TestRunApiResult.prototype['tags'] = undefined;






export default TestRunApiResult;

