/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TestStatusApiType.
* @enum {}
* @readonly
*/
export default class TestStatusApiType {
    
        /**
         * value: "Pending"
         * @const
         */
        "Pending" = "Pending";

    
        /**
         * value: "InProgress"
         * @const
         */
        "InProgress" = "InProgress";

    
        /**
         * value: "Succeeded"
         * @const
         */
        "Succeeded" = "Succeeded";

    
        /**
         * value: "Failed"
         * @const
         */
        "Failed" = "Failed";

    
        /**
         * value: "Incomplete"
         * @const
         */
        "Incomplete" = "Incomplete";

    

    /**
    * Returns a <code>TestStatusApiType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TestStatusApiType} The enum <code>TestStatusApiType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

