/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TestStatusApiType from './TestStatusApiType';

/**
 * The TestStatusApiResult model module.
 * @module model/TestStatusApiResult
 * @version 1.0.0
 */
class TestStatusApiResult {
    /**
     * Constructs a new <code>TestStatusApiResult</code>.
     * @alias module:model/TestStatusApiResult
     * @param id {String} 
     * @param type {module:model/TestStatusApiType} Collection of possible status types
     * @param code {String} 
     */
    constructor(id, type, code) { 
        
        TestStatusApiResult.initialize(this, id, type, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, type, code) { 
        obj['id'] = id;
        obj['type'] = type;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>TestStatusApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestStatusApiResult} obj Optional instance to populate.
     * @return {module:model/TestStatusApiResult} The populated <code>TestStatusApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestStatusApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], TestStatusApiType);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestStatusApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestStatusApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestStatusApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}

TestStatusApiResult.RequiredProperties = ["id", "type", "code"];

/**
 * @member {String} id
 */
TestStatusApiResult.prototype['id'] = undefined;

/**
 * Collection of possible status types
 * @member {module:model/TestStatusApiType} type
 */
TestStatusApiResult.prototype['type'] = undefined;

/**
 * @member {String} code
 */
TestStatusApiResult.prototype['code'] = undefined;






export default TestStatusApiResult;

