/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Int64RangeSelectorModel from './Int64RangeSelectorModel';
import TestResultOutcome from './TestResultOutcome';
import TestStatusApiType from './TestStatusApiType';

/**
 * The TestResultsFilterApiModel model module.
 * @module model/TestResultsFilterApiModel
 * @version 1.0.0
 */
class TestResultsFilterApiModel {
    /**
     * Constructs a new <code>TestResultsFilterApiModel</code>.
     * @alias module:model/TestResultsFilterApiModel
     */
    constructor() { 
        
        TestResultsFilterApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestResultsFilterApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestResultsFilterApiModel} obj Optional instance to populate.
     * @return {module:model/TestResultsFilterApiModel} The populated <code>TestResultsFilterApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestResultsFilterApiModel();

            if (data.hasOwnProperty('configurationIds')) {
                obj['configurationIds'] = ApiClient.convertToType(data['configurationIds'], ['String']);
            }
            if (data.hasOwnProperty('outcomes')) {
                obj['outcomes'] = ApiClient.convertToType(data['outcomes'], [TestResultOutcome]);
            }
            if (data.hasOwnProperty('statusCodes')) {
                obj['statusCodes'] = ApiClient.convertToType(data['statusCodes'], ['String']);
            }
            if (data.hasOwnProperty('statusTypes')) {
                obj['statusTypes'] = ApiClient.convertToType(data['statusTypes'], [TestStatusApiType]);
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('className')) {
                obj['className'] = ApiClient.convertToType(data['className'], 'String');
            }
            if (data.hasOwnProperty('autoTestGlobalIds')) {
                obj['autoTestGlobalIds'] = ApiClient.convertToType(data['autoTestGlobalIds'], ['Number']);
            }
            if (data.hasOwnProperty('autoTestTags')) {
                obj['autoTestTags'] = ApiClient.convertToType(data['autoTestTags'], ['String']);
            }
            if (data.hasOwnProperty('excludeAutoTestTags')) {
                obj['excludeAutoTestTags'] = ApiClient.convertToType(data['excludeAutoTestTags'], ['String']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], Int64RangeSelectorModel);
            }
            if (data.hasOwnProperty('testRunIds')) {
                obj['testRunIds'] = ApiClient.convertToType(data['testRunIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestResultsFilterApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestResultsFilterApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['configurationIds'])) {
            throw new Error("Expected the field `configurationIds` to be an array in the JSON data but got " + data['configurationIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['outcomes'])) {
            throw new Error("Expected the field `outcomes` to be an array in the JSON data but got " + data['outcomes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['statusCodes'])) {
            throw new Error("Expected the field `statusCodes` to be an array in the JSON data but got " + data['statusCodes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['statusTypes'])) {
            throw new Error("Expected the field `statusTypes` to be an array in the JSON data but got " + data['statusTypes']);
        }
        // ensure the json data is a string
        if (data['namespace'] && !(typeof data['namespace'] === 'string' || data['namespace'] instanceof String)) {
            throw new Error("Expected the field `namespace` to be a primitive type in the JSON string but got " + data['namespace']);
        }
        // ensure the json data is a string
        if (data['className'] && !(typeof data['className'] === 'string' || data['className'] instanceof String)) {
            throw new Error("Expected the field `className` to be a primitive type in the JSON string but got " + data['className']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['autoTestGlobalIds'])) {
            throw new Error("Expected the field `autoTestGlobalIds` to be an array in the JSON data but got " + data['autoTestGlobalIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['autoTestTags'])) {
            throw new Error("Expected the field `autoTestTags` to be an array in the JSON data but got " + data['autoTestTags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['excludeAutoTestTags'])) {
            throw new Error("Expected the field `excludeAutoTestTags` to be an array in the JSON data but got " + data['excludeAutoTestTags']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `duration`
        if (data['duration']) { // data not null
          Int64RangeSelectorModel.validateJSON(data['duration']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['testRunIds'])) {
            throw new Error("Expected the field `testRunIds` to be an array in the JSON data but got " + data['testRunIds']);
        }

        return true;
    }


}



/**
 * Specifies a test result configuration IDs to search for
 * @member {Array.<String>} configurationIds
 */
TestResultsFilterApiModel.prototype['configurationIds'] = undefined;

/**
 * Specifies a test result outcomes to search for
 * @member {Array.<module:model/TestResultOutcome>} outcomes
 */
TestResultsFilterApiModel.prototype['outcomes'] = undefined;

/**
 * Specifies a test result status codes to search for
 * @member {Array.<String>} statusCodes
 */
TestResultsFilterApiModel.prototype['statusCodes'] = undefined;

/**
 * Specifies a test result status types to search for
 * @member {Array.<module:model/TestStatusApiType>} statusTypes
 */
TestResultsFilterApiModel.prototype['statusTypes'] = undefined;

/**
 * Specifies a test result namespace to search for
 * @member {String} namespace
 */
TestResultsFilterApiModel.prototype['namespace'] = undefined;

/**
 * Specifies a test result class name to search for
 * @member {String} className
 */
TestResultsFilterApiModel.prototype['className'] = undefined;

/**
 * Specifies an autotest global IDs to search results for
 * @member {Array.<Number>} autoTestGlobalIds
 */
TestResultsFilterApiModel.prototype['autoTestGlobalIds'] = undefined;

/**
 * Specifies autotest tags to include in the search.
 * @member {Array.<String>} autoTestTags
 */
TestResultsFilterApiModel.prototype['autoTestTags'] = undefined;

/**
 * Specifies autotest tags to exclude from the search.
 * @member {Array.<String>} excludeAutoTestTags
 */
TestResultsFilterApiModel.prototype['excludeAutoTestTags'] = undefined;

/**
 * Specifies an autotest name to search results for
 * @member {String} name
 */
TestResultsFilterApiModel.prototype['name'] = undefined;

/**
 * Specifies a test result duration range to search for
 * @member {module:model/Int64RangeSelectorModel} duration
 */
TestResultsFilterApiModel.prototype['duration'] = undefined;

/**
 * Specifies a test result test run IDs to search for
 * @member {Array.<String>} testRunIds
 */
TestResultsFilterApiModel.prototype['testRunIds'] = undefined;






export default TestResultsFilterApiModel;

