/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignAttachmentApiModel from './AssignAttachmentApiModel';
import UpdateLinkApiModel from './UpdateLinkApiModel';

/**
 * The UpdateEmptyTestRunApiModel model module.
 * @module model/UpdateEmptyTestRunApiModel
 * @version 1.0.0
 */
class UpdateEmptyTestRunApiModel {
    /**
     * Constructs a new <code>UpdateEmptyTestRunApiModel</code>.
     * @alias module:model/UpdateEmptyTestRunApiModel
     * @param id {String} Test run unique identifier
     * @param name {String} Test run name
     */
    constructor(id, name) { 
        
        UpdateEmptyTestRunApiModel.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>UpdateEmptyTestRunApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEmptyTestRunApiModel} obj Optional instance to populate.
     * @return {module:model/UpdateEmptyTestRunApiModel} The populated <code>UpdateEmptyTestRunApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEmptyTestRunApiModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('launchSource')) {
                obj['launchSource'] = ApiClient.convertToType(data['launchSource'], 'String');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AssignAttachmentApiModel]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [UpdateLinkApiModel]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateEmptyTestRunApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateEmptyTestRunApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateEmptyTestRunApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['launchSource'] && !(typeof data['launchSource'] === 'string' || data['launchSource'] instanceof String)) {
            throw new Error("Expected the field `launchSource` to be a primitive type in the JSON string but got " + data['launchSource']);
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AssignAttachmentApiModel.validateJSON(item);
            };
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                UpdateLinkApiModel.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

UpdateEmptyTestRunApiModel.RequiredProperties = ["id", "name"];

/**
 * Test run unique identifier
 * @member {String} id
 */
UpdateEmptyTestRunApiModel.prototype['id'] = undefined;

/**
 * Test run name
 * @member {String} name
 */
UpdateEmptyTestRunApiModel.prototype['name'] = undefined;

/**
 * Test run description
 * @member {String} description
 */
UpdateEmptyTestRunApiModel.prototype['description'] = undefined;

/**
 * Test run launch source                Once launch source is specified it cannot be updated
 * @member {String} launchSource
 */
UpdateEmptyTestRunApiModel.prototype['launchSource'] = undefined;

/**
 * Collection of attachments related to the test run
 * @member {Array.<module:model/AssignAttachmentApiModel>} attachments
 */
UpdateEmptyTestRunApiModel.prototype['attachments'] = undefined;

/**
 * Collection of links related to the test run
 * @member {Array.<module:model/UpdateLinkApiModel>} links
 */
UpdateEmptyTestRunApiModel.prototype['links'] = undefined;

/**
 * Collection of tags to assign to the test run
 * @member {Array.<String>} tags
 */
UpdateEmptyTestRunApiModel.prototype['tags'] = undefined;






export default UpdateEmptyTestRunApiModel;

