/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WorkItemTypeModel.
* @enum {}
* @readonly
*/
export default class WorkItemTypeModel {
    
        /**
         * value: "TestCases"
         * @const
         */
        "TestCases" = "TestCases";

    
        /**
         * value: "CheckLists"
         * @const
         */
        "CheckLists" = "CheckLists";

    
        /**
         * value: "SharedSteps"
         * @const
         */
        "SharedSteps" = "SharedSteps";

    

    /**
    * Returns a <code>WorkItemTypeModel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WorkItemTypeModel} The enum <code>WorkItemTypeModel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

