/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IterationApiResult from './IterationApiResult';
import LinkShortApiResult from './LinkShortApiResult';
import WorkItemPriorityModel from './WorkItemPriorityModel';
import WorkItemSourceTypeModel from './WorkItemSourceTypeModel';
import WorkItemStates from './WorkItemStates';

/**
 * The WorkItemShortApiResult model module.
 * @module model/WorkItemShortApiResult
 * @version 1.0.0
 */
class WorkItemShortApiResult {
    /**
     * Constructs a new <code>WorkItemShortApiResult</code>.
     * @alias module:model/WorkItemShortApiResult
     * @param id {String} Work Item internal unique identifier
     * @param name {String} Work Item name
     * @param entityTypeName {String} Work Item type. Possible values: CheckLists, SharedSteps, TestCases
     * @param projectId {String} Project unique identifier
     * @param sectionId {String} Identifier of Section where Work Item is located
     * @param sectionName {String} Section name of Work Item
     * @param isAutomated {Boolean} Boolean flag determining whether Work Item is automated
     * @param globalId {Number} Work Item global identifier
     * @param duration {Number} Work Item duration
     * @param state {module:model/WorkItemStates} The current state of Work Item
     * @param priority {module:model/WorkItemPriorityModel} Work Item priority level
     * @param sourceType {module:model/WorkItemSourceTypeModel} Work Item priority level
     * @param isDeleted {Boolean} Flag determining whether Work Item is deleted
     * @param iterations {Array.<module:model/IterationApiResult>} Set of iterations related to Work Item
     * @param links {Array.<module:model/LinkShortApiResult>} Set of links related to Work Item
     */
    constructor(id, name, entityTypeName, projectId, sectionId, sectionName, isAutomated, globalId, duration, state, priority, sourceType, isDeleted, iterations, links) { 
        
        WorkItemShortApiResult.initialize(this, id, name, entityTypeName, projectId, sectionId, sectionName, isAutomated, globalId, duration, state, priority, sourceType, isDeleted, iterations, links);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, entityTypeName, projectId, sectionId, sectionName, isAutomated, globalId, duration, state, priority, sourceType, isDeleted, iterations, links) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['entityTypeName'] = entityTypeName;
        obj['projectId'] = projectId;
        obj['sectionId'] = sectionId;
        obj['sectionName'] = sectionName;
        obj['isAutomated'] = isAutomated;
        obj['globalId'] = globalId;
        obj['duration'] = duration;
        obj['state'] = state;
        obj['priority'] = priority;
        obj['sourceType'] = sourceType;
        obj['isDeleted'] = isDeleted;
        obj['iterations'] = iterations;
        obj['links'] = links;
    }

    /**
     * Constructs a <code>WorkItemShortApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkItemShortApiResult} obj Optional instance to populate.
     * @return {module:model/WorkItemShortApiResult} The populated <code>WorkItemShortApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkItemShortApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityTypeName')) {
                obj['entityTypeName'] = ApiClient.convertToType(data['entityTypeName'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('sectionId')) {
                obj['sectionId'] = ApiClient.convertToType(data['sectionId'], 'String');
            }
            if (data.hasOwnProperty('sectionName')) {
                obj['sectionName'] = ApiClient.convertToType(data['sectionName'], 'String');
            }
            if (data.hasOwnProperty('isAutomated')) {
                obj['isAutomated'] = ApiClient.convertToType(data['isAutomated'], 'Boolean');
            }
            if (data.hasOwnProperty('globalId')) {
                obj['globalId'] = ApiClient.convertToType(data['globalId'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': Object});
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], WorkItemStates);
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], WorkItemPriorityModel);
            }
            if (data.hasOwnProperty('sourceType')) {
                obj['sourceType'] = ApiClient.convertToType(data['sourceType'], WorkItemSourceTypeModel);
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('tagNames')) {
                obj['tagNames'] = ApiClient.convertToType(data['tagNames'], ['String']);
            }
            if (data.hasOwnProperty('iterations')) {
                obj['iterations'] = ApiClient.convertToType(data['iterations'], [IterationApiResult]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LinkShortApiResult]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkItemShortApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkItemShortApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkItemShortApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['entityTypeName'] && !(typeof data['entityTypeName'] === 'string' || data['entityTypeName'] instanceof String)) {
            throw new Error("Expected the field `entityTypeName` to be a primitive type in the JSON string but got " + data['entityTypeName']);
        }
        // ensure the json data is a string
        if (data['projectId'] && !(typeof data['projectId'] === 'string' || data['projectId'] instanceof String)) {
            throw new Error("Expected the field `projectId` to be a primitive type in the JSON string but got " + data['projectId']);
        }
        // ensure the json data is a string
        if (data['sectionId'] && !(typeof data['sectionId'] === 'string' || data['sectionId'] instanceof String)) {
            throw new Error("Expected the field `sectionId` to be a primitive type in the JSON string but got " + data['sectionId']);
        }
        // ensure the json data is a string
        if (data['sectionName'] && !(typeof data['sectionName'] === 'string' || data['sectionName'] instanceof String)) {
            throw new Error("Expected the field `sectionName` to be a primitive type in the JSON string but got " + data['sectionName']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tagNames'])) {
            throw new Error("Expected the field `tagNames` to be an array in the JSON data but got " + data['tagNames']);
        }
        if (data['iterations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['iterations'])) {
                throw new Error("Expected the field `iterations` to be an array in the JSON data but got " + data['iterations']);
            }
            // validate the optional field `iterations` (array)
            for (const item of data['iterations']) {
                IterationApiResult.validateJSON(item);
            };
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LinkShortApiResult.validateJSON(item);
            };
        }

        return true;
    }


}

WorkItemShortApiResult.RequiredProperties = ["id", "name", "entityTypeName", "projectId", "sectionId", "sectionName", "isAutomated", "globalId", "duration", "state", "priority", "sourceType", "isDeleted", "iterations", "links"];

/**
 * Work Item internal unique identifier
 * @member {String} id
 */
WorkItemShortApiResult.prototype['id'] = undefined;

/**
 * Work Item name
 * @member {String} name
 */
WorkItemShortApiResult.prototype['name'] = undefined;

/**
 * Work Item type. Possible values: CheckLists, SharedSteps, TestCases
 * @member {String} entityTypeName
 */
WorkItemShortApiResult.prototype['entityTypeName'] = undefined;

/**
 * Project unique identifier
 * @member {String} projectId
 */
WorkItemShortApiResult.prototype['projectId'] = undefined;

/**
 * Identifier of Section where Work Item is located
 * @member {String} sectionId
 */
WorkItemShortApiResult.prototype['sectionId'] = undefined;

/**
 * Section name of Work Item
 * @member {String} sectionName
 */
WorkItemShortApiResult.prototype['sectionName'] = undefined;

/**
 * Boolean flag determining whether Work Item is automated
 * @member {Boolean} isAutomated
 */
WorkItemShortApiResult.prototype['isAutomated'] = undefined;

/**
 * Work Item global identifier
 * @member {Number} globalId
 */
WorkItemShortApiResult.prototype['globalId'] = undefined;

/**
 * Work Item duration
 * @member {Number} duration
 */
WorkItemShortApiResult.prototype['duration'] = undefined;

/**
 * Work Item attributes
 * @member {Object.<String, Object>} attributes
 */
WorkItemShortApiResult.prototype['attributes'] = undefined;

/**
 * The current state of Work Item
 * @member {module:model/WorkItemStates} state
 */
WorkItemShortApiResult.prototype['state'] = undefined;

/**
 * Work Item priority level
 * @member {module:model/WorkItemPriorityModel} priority
 */
WorkItemShortApiResult.prototype['priority'] = undefined;

/**
 * Work Item priority level
 * @member {module:model/WorkItemSourceTypeModel} sourceType
 */
WorkItemShortApiResult.prototype['sourceType'] = undefined;

/**
 * Flag determining whether Work Item is deleted
 * @member {Boolean} isDeleted
 */
WorkItemShortApiResult.prototype['isDeleted'] = undefined;

/**
 * Array of tag names of Work Item
 * @member {Array.<String>} tagNames
 */
WorkItemShortApiResult.prototype['tagNames'] = undefined;

/**
 * Set of iterations related to Work Item
 * @member {Array.<module:model/IterationApiResult>} iterations
 */
WorkItemShortApiResult.prototype['iterations'] = undefined;

/**
 * Set of links related to Work Item
 * @member {Array.<module:model/LinkShortApiResult>} links
 */
WorkItemShortApiResult.prototype['links'] = undefined;






export default WorkItemShortApiResult;

