/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WorkItemSourceTypeModel.
* @enum {}
* @readonly
*/
export default class WorkItemSourceTypeModel {
    
        /**
         * value: "Manual"
         * @const
         */
        "Manual" = "Manual";

    
        /**
         * value: "AI"
         * @const
         */
        "AI" = "AI";

    

    /**
    * Returns a <code>WorkItemSourceTypeModel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WorkItemSourceTypeModel} The enum <code>WorkItemSourceTypeModel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

