/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AttachmentModel from '../model/AttachmentModel';
import ImageResizeType from '../model/ImageResizeType';
import ProblemDetails from '../model/ProblemDetails';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* Attachments service.
* @module api/AttachmentsApi
* @version 1.0.0
*/
export default class AttachmentsApi {

    /**
    * Constructs a new AttachmentsApi. 
    * @alias module:api/AttachmentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Object} opts Optional parameters
     * @param {Array.<File>} [files] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AttachmentModel>} and HTTP response
     */
    adaptersAttachmentsBulkPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'files': this.apiClient.buildCollectionParam(opts['files'], 'passthrough')
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = [AttachmentModel];
      return this.apiClient.callApi(
        '/adapters/attachments/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {Array.<File>} opts.files 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AttachmentModel>}
     */
    adaptersAttachmentsBulkPost(opts) {
      return this.adaptersAttachmentsBulkPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Download attachment file
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Number} [width] Width of the result image
     * @param {Number} [height] Height of the result image
     * @param {module:model/ImageResizeType} [resizeType] Type of resizing to apply to the result image
     * @param {String} [backgroundColor] Color of the background if the `resizeType` is `AddBackgroundStripes`
     * @param {Boolean} [preview] If image must be converted to a preview (lower quality, no animation)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAttachmentsIdGetWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAttachmentsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'width': opts['width'],
        'height': opts['height'],
        'resizeType': opts['resizeType'],
        'backgroundColor': opts['backgroundColor'],
        'preview': opts['preview']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/attachments/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Download attachment file
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.width Width of the result image
     * @param {Number} opts.height Height of the result image
     * @param {module:model/ImageResizeType} opts.resizeType Type of resizing to apply to the result image
     * @param {String} opts.backgroundColor Color of the background if the `resizeType` is `AddBackgroundStripes`
     * @param {Boolean} opts.preview If image must be converted to a preview (lower quality, no animation)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAttachmentsIdGet(id, opts) {
      return this.adaptersAttachmentsIdGetWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload new attachment file
     * File size is restricted to 1 GB (1 073 741 824 bytes)
     * @param {Object} opts Optional parameters
     * @param {File} [file] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AttachmentModel} and HTTP response
     */
    adaptersAttachmentsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = AttachmentModel;
      return this.apiClient.callApi(
        '/adapters/attachments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload new attachment file
     * File size is restricted to 1 GB (1 073 741 824 bytes)
     * @param {Object} opts Optional parameters
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AttachmentModel}
     */
    adaptersAttachmentsPost(opts) {
      return this.adaptersAttachmentsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
