/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateParameterApiModel from '../model/CreateParameterApiModel';
import ParameterApiResult from '../model/ParameterApiResult';
import ParametersFilterApiModel from '../model/ParametersFilterApiModel';
import ProblemDetails from '../model/ProblemDetails';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* Parameters service.
* @module api/ParametersApi
* @version 1.0.0
*/
export default class ParametersApi {

    /**
    * Constructs a new ParametersApi. 
    * @alias module:api/ParametersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get parameter by ID
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ParameterApiResult} and HTTP response
     */
    adaptersParametersIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersParametersIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ParameterApiResult;
      return this.apiClient.callApi(
        '/adapters/parameters/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get parameter by ID
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ParameterApiResult}
     */
    adaptersParametersIdGet(id) {
      return this.adaptersParametersIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create parameter
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateParameterApiModel} [createParameterApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ParameterApiResult} and HTTP response
     */
    adaptersParametersPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createParameterApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ParameterApiResult;
      return this.apiClient.callApi(
        '/adapters/parameters', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create parameter
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateParameterApiModel} opts.createParameterApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ParameterApiResult}
     */
    adaptersParametersPost(opts) {
      return this.adaptersParametersPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search for parameters
     * @param {Object} opts Optional parameters
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @param {module:model/ParametersFilterApiModel} [parametersFilterApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ParameterApiResult>} and HTTP response
     */
    adaptersParametersSearchPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['parametersFilterApiModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [ParameterApiResult];
      return this.apiClient.callApi(
        '/adapters/parameters/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for parameters
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/ParametersFilterApiModel} opts.parametersFilterApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ParameterApiResult>}
     */
    adaptersParametersSearchPost(opts) {
      return this.adaptersParametersSearchPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
