/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeletionState from '../model/DeletionState';
import ProblemDetails from '../model/ProblemDetails';
import SectionPostModel from '../model/SectionPostModel';
import SectionWithStepsModel from '../model/SectionWithStepsModel';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* Sections service.
* @module api/SectionsApi
* @version 1.0.0
*/
export default class SectionsApi {

    /**
    * Constructs a new SectionsApi. 
    * @alias module:api/SectionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get section
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/DeletionState} [isDeleted] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SectionWithStepsModel} and HTTP response
     */
    adaptersSectionsIdGetWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersSectionsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'isDeleted': opts['isDeleted']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SectionWithStepsModel;
      return this.apiClient.callApi(
        '/adapters/sections/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get section
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/DeletionState} opts.isDeleted 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SectionWithStepsModel}
     */
    adaptersSectionsIdGet(id, opts) {
      return this.adaptersSectionsIdGetWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create section
     * @param {Object} opts Optional parameters
     * @param {module:model/SectionPostModel} [sectionPostModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SectionWithStepsModel} and HTTP response
     */
    adaptersSectionsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['sectionPostModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SectionWithStepsModel;
      return this.apiClient.callApi(
        '/adapters/sections', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create section
     * @param {Object} opts Optional parameters
     * @param {module:model/SectionPostModel} opts.sectionPostModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SectionWithStepsModel}
     */
    adaptersSectionsPost(opts) {
      return this.adaptersSectionsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
