/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateWorkItemApiModel from '../model/CreateWorkItemApiModel';
import ProblemDetails from '../model/ProblemDetails';
import ValidationProblemDetails from '../model/ValidationProblemDetails';
import WorkItemApiResult from '../model/WorkItemApiResult';
import WorkItemSelectApiModel from '../model/WorkItemSelectApiModel';
import WorkItemShortApiResult from '../model/WorkItemShortApiResult';

/**
* WorkItems service.
* @module api/WorkItemsApi
* @version 1.0.0
*/
export default class WorkItemsApi {

    /**
    * Constructs a new WorkItemsApi. 
    * @alias module:api/WorkItemsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get Test Case, Checklist or Shared Step by Id or GlobalId
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {String} [versionId] 
     * @param {Number} [versionNumber] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkItemApiResult} and HTTP response
     */
    adaptersWorkItemsIdGetWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersWorkItemsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'versionId': opts['versionId'],
        'versionNumber': opts['versionNumber']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WorkItemApiResult;
      return this.apiClient.callApi(
        '/adapters/workItems/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Test Case, Checklist or Shared Step by Id or GlobalId
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {String} opts.versionId 
     * @param {Number} opts.versionNumber 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkItemApiResult}
     */
    adaptersWorkItemsIdGet(id, opts) {
      return this.adaptersWorkItemsIdGetWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Creates work item
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateWorkItemApiModel} [createWorkItemApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/WorkItemApiResult} and HTTP response
     */
    adaptersWorkItemsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createWorkItemApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = WorkItemApiResult;
      return this.apiClient.callApi(
        '/adapters/workItems', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates work item
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateWorkItemApiModel} opts.createWorkItemApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/WorkItemApiResult}
     */
    adaptersWorkItemsPost(opts) {
      return this.adaptersWorkItemsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search for work items
     * @param {Object} opts Optional parameters
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @param {module:model/WorkItemSelectApiModel} [workItemSelectApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/WorkItemShortApiResult>} and HTTP response
     */
    adaptersWorkItemsSearchPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['workItemSelectApiModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [WorkItemShortApiResult];
      return this.apiClient.callApi(
        '/adapters/workItems/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for work items
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/WorkItemSelectApiModel} opts.workItemSelectApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/WorkItemShortApiResult>}
     */
    adaptersWorkItemsSearchPost(opts) {
      return this.adaptersWorkItemsSearchPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
