/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AutoTestApiResult from '../model/AutoTestApiResult';
import AutoTestCreateApiModel from '../model/AutoTestCreateApiModel';
import AutoTestModel from '../model/AutoTestModel';
import AutoTestSearchApiModel from '../model/AutoTestSearchApiModel';
import AutoTestUpdateApiModel from '../model/AutoTestUpdateApiModel';
import AutoTestWorkItemIdentifierApiResult from '../model/AutoTestWorkItemIdentifierApiResult';
import Operation from '../model/Operation';
import ProblemDetails from '../model/ProblemDetails';
import ValidationProblemDetails from '../model/ValidationProblemDetails';
import WorkItemIdApiModel from '../model/WorkItemIdApiModel';

/**
* AutoTests service.
* @module api/AutoTestsApi
* @version 1.0.0
*/
export default class AutoTestsApi {

    /**
    * Constructs a new AutoTestsApi. 
    * @alias module:api/AutoTestsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create multiple autotests
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestCreateApiModel>} [autoTestCreateApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AutoTestApiResult>} and HTTP response
     */
    adaptersAutoTestsBulkPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['autoTestCreateApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [AutoTestApiResult];
      return this.apiClient.callApi(
        '/adapters/autoTests/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create multiple autotests
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestCreateApiModel>} opts.autoTestCreateApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AutoTestApiResult>}
     */
    adaptersAutoTestsBulkPost(opts) {
      return this.adaptersAutoTestsBulkPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update multiple autotests
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestUpdateApiModel>} [autoTestUpdateApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAutoTestsBulkPutWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['autoTestUpdateApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/autoTests/bulk', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update multiple autotests
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestUpdateApiModel>} opts.autoTestUpdateApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAutoTestsBulkPut(opts) {
      return this.adaptersAutoTestsBulkPutWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {String} [projectId] Project internal ID
     * @param {String} [externalId] Autotest external ID
     * @param {Number} [globalId] Autotest global ID
     * @param {String} [namespace] Namespace in which autotest is located
     * @param {Boolean} [isNamespaceNull] OBSOLETE: Use `includeEmptyNamespaces` instead
     * @param {Boolean} [includeEmptyNamespaces] If result must contain autotests without namespace
     * @param {String} [className] Name of class in which autotest is located
     * @param {Boolean} [isClassnameNull] OBSOLETE: Use `includeEmptyClassNames` instead
     * @param {Boolean} [includeEmptyClassNames] If result must contain autotests without class
     * @param {Boolean} [isDeleted] OBSOLETE: Use `deleted` instead
     * @param {Boolean} [deleted] Is autotest deleted
     * @param {Array.<String>} [labels] Include only autotests with provided labels
     * @param {Number} [stabilityMinimal] OBSOLETE: Use `minStability` instead
     * @param {Number} [minStability] Minimum stability value of autotest
     * @param {Number} [stabilityMaximal] OBSOLETE: Use `maxStability` instead
     * @param {Number} [maxStability] Maximum stability value of autotest
     * @param {Boolean} [isFlaky] OBSOLETE: Use `flaky` instead
     * @param {Boolean} [flaky] Is autotest marked as \"Flaky\"
     * @param {Boolean} [includeSteps] If result must also include autotest steps
     * @param {Boolean} [includeLabels] If result must also include autotest labels
     * @param {String} [externalKey] External key of autotest
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AutoTestModel>} and HTTP response
     */
    adaptersAutoTestsGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'projectId': opts['projectId'],
        'externalId': opts['externalId'],
        'globalId': opts['globalId'],
        'namespace': opts['namespace'],
        'isNamespaceNull': opts['isNamespaceNull'],
        'includeEmptyNamespaces': opts['includeEmptyNamespaces'],
        'className': opts['className'],
        'isClassnameNull': opts['isClassnameNull'],
        'includeEmptyClassNames': opts['includeEmptyClassNames'],
        'isDeleted': opts['isDeleted'],
        'deleted': opts['deleted'],
        'labels': this.apiClient.buildCollectionParam(opts['labels'], 'multi'),
        'stabilityMinimal': opts['stabilityMinimal'],
        'minStability': opts['minStability'],
        'stabilityMaximal': opts['stabilityMaximal'],
        'maxStability': opts['maxStability'],
        'isFlaky': opts['isFlaky'],
        'flaky': opts['flaky'],
        'includeSteps': opts['includeSteps'],
        'includeLabels': opts['includeLabels'],
        'externalKey': opts['externalKey'],
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AutoTestModel];
      return this.apiClient.callApi(
        '/adapters/autoTests', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.projectId Project internal ID
     * @param {String} opts.externalId Autotest external ID
     * @param {Number} opts.globalId Autotest global ID
     * @param {String} opts.namespace Namespace in which autotest is located
     * @param {Boolean} opts.isNamespaceNull OBSOLETE: Use `includeEmptyNamespaces` instead
     * @param {Boolean} opts.includeEmptyNamespaces If result must contain autotests without namespace
     * @param {String} opts.className Name of class in which autotest is located
     * @param {Boolean} opts.isClassnameNull OBSOLETE: Use `includeEmptyClassNames` instead
     * @param {Boolean} opts.includeEmptyClassNames If result must contain autotests without class
     * @param {Boolean} opts.isDeleted OBSOLETE: Use `deleted` instead
     * @param {Boolean} opts.deleted Is autotest deleted
     * @param {Array.<String>} opts.labels Include only autotests with provided labels
     * @param {Number} opts.stabilityMinimal OBSOLETE: Use `minStability` instead
     * @param {Number} opts.minStability Minimum stability value of autotest
     * @param {Number} opts.stabilityMaximal OBSOLETE: Use `maxStability` instead
     * @param {Number} opts.maxStability Maximum stability value of autotest
     * @param {Boolean} opts.isFlaky OBSOLETE: Use `flaky` instead
     * @param {Boolean} opts.flaky Is autotest marked as \"Flaky\"
     * @param {Boolean} opts.includeSteps If result must also include autotest steps
     * @param {Boolean} opts.includeLabels If result must also include autotest labels
     * @param {String} opts.externalKey External key of autotest
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AutoTestModel>}
     */
    adaptersAutoTestsGet(opts) {
      return this.adaptersAutoTestsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get autotest by internal or global ID
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AutoTestApiResult} and HTTP response
     */
    adaptersAutoTestsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAutoTestsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AutoTestApiResult;
      return this.apiClient.callApi(
        '/adapters/autoTests/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get autotest by internal or global ID
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AutoTestApiResult}
     */
    adaptersAutoTestsIdGet(id) {
      return this.adaptersAutoTestsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Patch auto test
     * See <a href=\"https://www.rfc-editor.org/rfc/rfc6902\" target=\"_blank\">RFC 6902: JavaScript Object Notation (JSON) Patch</a> for details
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/Operation>} [operation] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAutoTestsIdPatchWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['operation'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAutoTestsIdPatch");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/autoTests/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Patch auto test
     * See <a href=\"https://www.rfc-editor.org/rfc/rfc6902\" target=\"_blank\">RFC 6902: JavaScript Object Notation (JSON) Patch</a> for details
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/Operation>} opts.operation 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAutoTestsIdPatch(id, opts) {
      return this.adaptersAutoTestsIdPatchWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Unlink autotest from work item
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {String} [workItemId] Internal (UUID) or global (integer) identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAutoTestsIdWorkItemsDeleteWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAutoTestsIdWorkItemsDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'workItemId': opts['workItemId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/autoTests/{id}/work-items', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Unlink autotest from work item
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {String} opts.workItemId Internal (UUID) or global (integer) identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAutoTestsIdWorkItemsDelete(id, opts) {
      return this.adaptersAutoTestsIdWorkItemsDeleteWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get work items linked to autotest
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {Boolean} [isDeleted] 
     * @param {Boolean} [isWorkItemDeleted = false)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AutoTestWorkItemIdentifierApiResult>} and HTTP response
     */
    adaptersAutoTestsIdWorkItemsGetWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAutoTestsIdWorkItemsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'isDeleted': opts['isDeleted'],
        'isWorkItemDeleted': opts['isWorkItemDeleted']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AutoTestWorkItemIdentifierApiResult];
      return this.apiClient.callApi(
        '/adapters/autoTests/{id}/work-items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get work items linked to autotest
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.isDeleted 
     * @param {Boolean} opts.isWorkItemDeleted  (default to false)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AutoTestWorkItemIdentifierApiResult>}
     */
    adaptersAutoTestsIdWorkItemsGet(id, opts) {
      return this.adaptersAutoTestsIdWorkItemsGetWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Link autotest with work items
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {module:model/WorkItemIdApiModel} [workItemIdApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAutoTestsIdWorkItemsPostWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['workItemIdApiModel'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersAutoTestsIdWorkItemsPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/autoTests/{id}/work-items', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Link autotest with work items
     * @param {String} id Internal (UUID) or global (integer) identifier
     * @param {Object} opts Optional parameters
     * @param {module:model/WorkItemIdApiModel} opts.workItemIdApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAutoTestsIdWorkItemsPost(id, opts) {
      return this.adaptersAutoTestsIdWorkItemsPostWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create autotest
     * @param {Object} opts Optional parameters
     * @param {module:model/AutoTestCreateApiModel} [autoTestCreateApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AutoTestApiResult} and HTTP response
     */
    adaptersAutoTestsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['autoTestCreateApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AutoTestApiResult;
      return this.apiClient.callApi(
        '/adapters/autoTests', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create autotest
     * @param {Object} opts Optional parameters
     * @param {module:model/AutoTestCreateApiModel} opts.autoTestCreateApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AutoTestApiResult}
     */
    adaptersAutoTestsPost(opts) {
      return this.adaptersAutoTestsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update autotest
     * @param {Object} opts Optional parameters
     * @param {module:model/AutoTestUpdateApiModel} [autoTestUpdateApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersAutoTestsPutWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['autoTestUpdateApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/autoTests', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update autotest
     * @param {Object} opts Optional parameters
     * @param {module:model/AutoTestUpdateApiModel} opts.autoTestUpdateApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersAutoTestsPut(opts) {
      return this.adaptersAutoTestsPutWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search for autotests
     * @param {Object} opts Optional parameters
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @param {module:model/AutoTestSearchApiModel} [autoTestSearchApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AutoTestApiResult>} and HTTP response
     */
    adaptersAutoTestsSearchPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['autoTestSearchApiModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [AutoTestApiResult];
      return this.apiClient.callApi(
        '/adapters/autoTests/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for autotests
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/AutoTestSearchApiModel} opts.autoTestSearchApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AutoTestApiResult>}
     */
    adaptersAutoTestsSearchPost(opts) {
      return this.adaptersAutoTestsSearchPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
