/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CustomAttributeApiResult from '../model/CustomAttributeApiResult';
import CustomAttributeSearchApiModel from '../model/CustomAttributeSearchApiModel';
import CustomAttributeSearchApiResult from '../model/CustomAttributeSearchApiResult';
import GlobalCustomAttributePostApiModel from '../model/GlobalCustomAttributePostApiModel';
import GlobalCustomAttributeUpdateApiModel from '../model/GlobalCustomAttributeUpdateApiModel';
import ProblemDetails from '../model/ProblemDetails';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* CustomAttributes service.
* @module api/CustomAttributesApi
* @version 1.0.0
*/
export default class CustomAttributesApi {

    /**
    * Constructs a new CustomAttributesApi. 
    * @alias module:api/CustomAttributesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Update global attribute
     * @param {String} id Unique ID of attribute
     * @param {Object} opts Optional parameters
     * @param {module:model/GlobalCustomAttributeUpdateApiModel} [globalCustomAttributeUpdateApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CustomAttributeApiResult} and HTTP response
     */
    adaptersCustomAttributesGlobalIdPutWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['globalCustomAttributeUpdateApiModel'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersCustomAttributesGlobalIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Identity.Application'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CustomAttributeApiResult;
      return this.apiClient.callApi(
        '/adapters/customAttributes/global/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update global attribute
     * @param {String} id Unique ID of attribute
     * @param {Object} opts Optional parameters
     * @param {module:model/GlobalCustomAttributeUpdateApiModel} opts.globalCustomAttributeUpdateApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CustomAttributeApiResult}
     */
    adaptersCustomAttributesGlobalIdPut(id, opts) {
      return this.adaptersCustomAttributesGlobalIdPutWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create global attribute
     * @param {Object} opts Optional parameters
     * @param {module:model/GlobalCustomAttributePostApiModel} [globalCustomAttributePostApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CustomAttributeApiResult} and HTTP response
     */
    adaptersCustomAttributesGlobalPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['globalCustomAttributePostApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Identity.Application'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CustomAttributeApiResult;
      return this.apiClient.callApi(
        '/adapters/customAttributes/global', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create global attribute
     * @param {Object} opts Optional parameters
     * @param {module:model/GlobalCustomAttributePostApiModel} opts.globalCustomAttributePostApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CustomAttributeApiResult}
     */
    adaptersCustomAttributesGlobalPost(opts) {
      return this.adaptersCustomAttributesGlobalPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get attribute by ID
     * @param {String} id Unique ID of attribute
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CustomAttributeApiResult} and HTTP response
     */
    adaptersCustomAttributesIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersCustomAttributesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Identity.Application'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CustomAttributeApiResult;
      return this.apiClient.callApi(
        '/adapters/customAttributes/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get attribute by ID
     * @param {String} id Unique ID of attribute
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CustomAttributeApiResult}
     */
    adaptersCustomAttributesIdGet(id) {
      return this.adaptersCustomAttributesIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search for attributes
     * @param {Object} opts Optional parameters
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @param {module:model/CustomAttributeSearchApiModel} [customAttributeSearchApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CustomAttributeSearchApiResult>} and HTTP response
     */
    adaptersCustomAttributesSearchPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['customAttributeSearchApiModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Identity.Application'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CustomAttributeSearchApiResult];
      return this.apiClient.callApi(
        '/adapters/customAttributes/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for attributes
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/CustomAttributeSearchApiModel} opts.customAttributeSearchApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CustomAttributeSearchApiResult>}
     */
    adaptersCustomAttributesSearchPost(opts) {
      return this.adaptersCustomAttributesSearchPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
