/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateProjectApiModel from '../model/CreateProjectApiModel';
import DetailedProjectApiResult from '../model/DetailedProjectApiResult';
import ProblemDetails from '../model/ProblemDetails';
import ProjectApiResult from '../model/ProjectApiResult';
import ProjectsFilterModel from '../model/ProjectsFilterModel';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* Projects service.
* @module api/ProjectsApi
* @version 1.0.0
*/
export default class ProjectsApi {

    /**
    * Constructs a new ProjectsApi. 
    * @alias module:api/ProjectsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add global attributes to project
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} [requestBody] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersProjectsIdAttributesGlobalPostWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['requestBody'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersProjectsIdAttributesGlobalPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/projects/{id}/attributes/global', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add global attributes to project
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.requestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersProjectsIdAttributesGlobalPost(id, opts) {
      return this.adaptersProjectsIdAttributesGlobalPostWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get project by ID
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DetailedProjectApiResult} and HTTP response
     */
    adaptersProjectsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersProjectsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DetailedProjectApiResult;
      return this.apiClient.callApi(
        '/adapters/projects/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get project by ID
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DetailedProjectApiResult}
     */
    adaptersProjectsIdGet(id) {
      return this.adaptersProjectsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create project
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateProjectApiModel} [createProjectApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProjectApiResult} and HTTP response
     */
    adaptersProjectsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createProjectApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ProjectApiResult;
      return this.apiClient.callApi(
        '/adapters/projects', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create project
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateProjectApiModel} opts.createProjectApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProjectApiResult}
     */
    adaptersProjectsPost(opts) {
      return this.adaptersProjectsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search for projects
     * @param {Object} opts Optional parameters
     * @param {Number} [skip] Amount of items to be skipped (offset)
     * @param {Number} [take] Amount of items to be taken (limit)
     * @param {String} [orderBy] SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} [searchField] Property name for searching
     * @param {String} [searchValue] Value for searching
     * @param {module:model/ProjectsFilterModel} [projectsFilterModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ProjectApiResult>} and HTTP response
     */
    adaptersProjectsSearchPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['projectsFilterModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [ProjectApiResult];
      return this.apiClient.callApi(
        '/adapters/projects/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search for projects
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/ProjectsFilterModel} opts.projectsFilterModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ProjectApiResult>}
     */
    adaptersProjectsSearchPost(opts) {
      return this.adaptersProjectsSearchPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
