/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AutoTestResultsForTestRunModel from '../model/AutoTestResultsForTestRunModel';
import CreateEmptyTestRunApiModel from '../model/CreateEmptyTestRunApiModel';
import ManualRerunApiResult from '../model/ManualRerunApiResult';
import ManualRerunSelectTestResultsApiModel from '../model/ManualRerunSelectTestResultsApiModel';
import ProblemDetails from '../model/ProblemDetails';
import TestRunApiResult from '../model/TestRunApiResult';
import UpdateEmptyTestRunApiModel from '../model/UpdateEmptyTestRunApiModel';
import ValidationProblemDetails from '../model/ValidationProblemDetails';

/**
* TestRuns service.
* @module api/TestRunsApi
* @version 1.0.0
*/
export default class TestRunsApi {

    /**
    * Constructs a new TestRunsApi. 
    * @alias module:api/TestRunsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Complete TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersTestRunsIdCompletePostWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdCompletePost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Complete TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersTestRunsIdCompletePost(id) {
      return this.adaptersTestRunsIdCompletePostWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get TestRun by Id
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestRunApiResult} and HTTP response
     */
    adaptersTestRunsIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TestRunApiResult;
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get TestRun by Id
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestRunApiResult}
     */
    adaptersTestRunsIdGet(id) {
      return this.adaptersTestRunsIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Manual autotests rerun in test run
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/ManualRerunSelectTestResultsApiModel} [manualRerunSelectTestResultsApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ManualRerunApiResult} and HTTP response
     */
    adaptersTestRunsIdRerunsPostWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['manualRerunSelectTestResultsApiModel'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdRerunsPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ManualRerunApiResult;
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}/reruns', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Manual autotests rerun in test run
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/ManualRerunSelectTestResultsApiModel} opts.manualRerunSelectTestResultsApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ManualRerunApiResult}
     */
    adaptersTestRunsIdRerunsPost(id, opts) {
      return this.adaptersTestRunsIdRerunsPostWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Start TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersTestRunsIdStartPostWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdStartPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}/start', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Start TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersTestRunsIdStartPost(id) {
      return this.adaptersTestRunsIdStartPostWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Stop TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersTestRunsIdStopPostWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdStopPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}/stop', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Stop TestRun
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersTestRunsIdStopPost(id) {
      return this.adaptersTestRunsIdStopPostWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Send test results to the test runs in the system
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestResultsForTestRunModel>} [autoTestResultsForTestRunModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<String>} and HTTP response
     */
    adaptersTestRunsIdTestResultsPostWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['autoTestResultsForTestRunModel'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling adaptersTestRunsIdTestResultsPost");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/adapters/testRuns/{id}/test-results', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Send test results to the test runs in the system
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/AutoTestResultsForTestRunModel>} opts.autoTestResultsForTestRunModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<String>}
     */
    adaptersTestRunsIdTestResultsPost(id, opts) {
      return this.adaptersTestRunsIdTestResultsPostWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create empty TestRun
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateEmptyTestRunApiModel} [createEmptyTestRunApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestRunApiResult} and HTTP response
     */
    adaptersTestRunsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createEmptyTestRunApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TestRunApiResult;
      return this.apiClient.callApi(
        '/adapters/testRuns', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create empty TestRun
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateEmptyTestRunApiModel} opts.createEmptyTestRunApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestRunApiResult}
     */
    adaptersTestRunsPost(opts) {
      return this.adaptersTestRunsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update empty TestRun
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateEmptyTestRunApiModel} [updateEmptyTestRunApiModel] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    adaptersTestRunsPutWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['updateEmptyTestRunApiModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['PrivateToken', 'Cookies'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/adapters/testRuns', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update empty TestRun
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateEmptyTestRunApiModel} opts.updateEmptyTestRunApiModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    adaptersTestRunsPut(opts) {
      return this.adaptersTestRunsPutWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
